// MaxWord vocabulary bank — sourced from the A-Level GP Vocabulary Masterlist (200 words).
// This file is pure data — no app logic. Safe to hand-edit or extend without touching index.html.
//
// Data shape: each entry has a 3-tier progression (basic -> intermediate -> advanced).
// The QUESTION shown to the player is always the ADVANCED word.
// The 3 answer choices are drawn from BASIC/INTERMEDIATE words only, with exactly
// one of the three being the correct basic/intermediate match for that advanced word.
// `sentence` is a contextual example sentence demonstrating the advanced word in use.

export const CATEGORIES = [
  { key: "gp", label: "GP Vocabulary" },
];

export const WORDS = [
  { id: "w001", basic: "Show", intermediate: "Demonstrate", word: "Evince", category: "gp", sentence: "The policy proposals evince a clear intent to prioritize sustainability over short-term profits." },
  { id: "w002", basic: "Hide", intermediate: "Conceal", word: "Obfuscate", category: "gp", sentence: "State media often attempts to obfuscate the reality of financial crises through selective data reporting." },
  { id: "w003", basic: "Help", intermediate: "Assist", word: "Facilitate", category: "gp", sentence: "Digital infrastructure projects can facilitate cross-border trade in developing regions." },
  { id: "w004", basic: "Stop", intermediate: "Prevent", word: "Thwart", category: "gp", sentence: "Robust security regulations managed to thwart cyber threats targeted at national infrastructure." },
  { id: "w005", basic: "Start", intermediate: "Initiate", word: "Instigate", category: "gp", sentence: "Unfair labor conditions helped to instigate widespread union strikes across the manufacturing sector." },
  { id: "w006", basic: "Cause", intermediate: "Produce", word: "Engender", category: "gp", sentence: "Unregulated social media platforms can engender deep political polarization within democratic societies." },
  { id: "w007", basic: "Spread", intermediate: "Scatter", word: "Disseminate", category: "gp", sentence: "Independent news outlets work to disseminate accurate information during public emergencies." },
  { id: "w008", basic: "Gather", intermediate: "Accumulate", word: "Aggregate", category: "gp", sentence: "Data analytics tools aggregate consumer metrics to predict global market movements." },
  { id: "w009", basic: "Build", intermediate: "Construct", word: "Fabricate", category: "gp", sentence: "Bad actors can easily fabricate convincing deepfake videos using open-source tools." },
  { id: "w010", basic: "Destroy", intermediate: "Devastate", word: "Annihilate", category: "gp", sentence: "Nuclear proliferation risks weapons systems that could annihilate major population centers." },
  { id: "w011", basic: "Weak", intermediate: "Fragile", word: "Precarious", category: "gp", sentence: "Laborers in gig economy positions remain in precarious financial situations without traditional safety nets." },
  { id: "w012", basic: "Strong", intermediate: "Robust", word: "Resilient", category: "gp", sentence: "A diversified economy makes a country far more resilient against external supply chain shocks." },
  { id: "w013", basic: "Rich", intermediate: "Wealthy", word: "Affluent", category: "gp", sentence: "Consumers in affluent nations account for a disproportionate share of international resource consumption." },
  { id: "w014", basic: "Poor", intermediate: "Needy", word: "Destitute", category: "gp", sentence: "Natural disasters can instantly leave entire rural communities completely destitute." },
  { id: "w015", basic: "Large", intermediate: "Substantial", word: "Prodigious", category: "gp", sentence: "The tech sector requires prodigious amounts of electricity to sustain growing data centers." },
  { id: "w016", basic: "Small", intermediate: "Minor", word: "Negligible", category: "gp", sentence: "Statistical models show that the environmental impact of the new policy will be negligible." },
  { id: "w017", basic: "Shortage", intermediate: "Scarcity", word: "Paucity", category: "gp", sentence: "A persistent paucity of skilled healthcare staff hinders rural clinic operations worldwide." },
  { id: "w018", basic: "Plenty", intermediate: "Abundance", word: "Profusion", category: "gp", sentence: "The profusion of online streaming options has fragmented traditional media audiences." },
  { id: "w019", basic: "Old", intermediate: "Outdated", word: "Anachronistic", category: "gp", sentence: "Relying solely on coal power generation is increasingly viewed as anachronistic in the modern energy landscape." },
  { id: "w020", basic: "New", intermediate: "Novel", word: "Unprecedented", category: "gp", sentence: "The rapid adoption of generative AI represents an unprecedented shift in information management." },
  { id: "w021", basic: "Quick", intermediate: "Rapid", word: "Expeditious", category: "gp", sentence: "International relief efforts require expeditious administrative procedures to save lives." },
  { id: "w022", basic: "Slow", intermediate: "Sluggish", word: "Lethargic", category: "gp", sentence: "Bureaucratic friction can cause a lethargic official response to sudden economic crises." },
  { id: "w023", basic: "Clear", intermediate: "Apparent", word: "Manifest", category: "gp", sentence: "The consequences of climate change have become manifest through frequent extreme weather events." },
  { id: "w024", basic: "Secret", intermediate: "Hidden", word: "Clandestine", category: "gp", sentence: "Intelligence agencies often conduct clandestine operations to safeguard national security interests." },
  { id: "w025", basic: "False", intermediate: "Fraudulent", word: "Spurious", category: "gp", sentence: "Academic journals rigorously peer-review submissions to eliminate spurious research claims." },
  { id: "w026", basic: "True", intermediate: "Genuine", word: "Authentic", category: "gp", sentence: "Archival documents provide authentic historical insights into early diplomatic treaties." },
  { id: "w027", basic: "Simple", intermediate: "Basic", word: "Rudimentary", category: "gp", sentence: "Early space initiatives operated with rudimentary computer systems compared to modern standards." },
  { id: "w028", basic: "Complex", intermediate: "Intricate", word: "Labyrinthine", category: "gp", sentence: "Navigating the labyrinthine legal systems of international trade requires specialized legal counsel." },
  { id: "w029", basic: "Dangerous", intermediate: "Perilous", word: "Hazardous", category: "gp", sentence: "Transporting industrial waste through urban zones remains an inherently hazardous operation." },
  { id: "w030", basic: "Safe", intermediate: "Secure", word: "Invulnerable", category: "gp", sentence: "No financial institution can consider itself completely invulnerable to global economic recessions." },
  { id: "w031", basic: "Harmful", intermediate: "Injurious", word: "Inimical", category: "gp", sentence: "High import tariffs can prove inimical to long-term international economic cooperation." },
  { id: "w032", basic: "Useful", intermediate: "Beneficial", word: "Advantageous", category: "gp", sentence: "Tax incentives for clean energy startups make investment far more advantageous." },
  { id: "w033", basic: "Equal", intermediate: "Equivalent", word: "Tantamount", category: "gp", sentence: "Failing to act against corporate corruption is tantamount to endorsing unlawful behavior." },
  { id: "w034", basic: "Different", intermediate: "Distinct", word: "Disparate", category: "gp", sentence: "A successful coalition must harmonize the disparate political agendas of its member groups." },
  { id: "w035", basic: "Continuous", intermediate: "Unceasing", word: "Incessant", category: "gp", sentence: "The incessant news cycle often prioritizes sensational breaking stories over deep analysis." },
  { id: "w036", basic: "Temporary", intermediate: "Transient", word: "Ephemeral", category: "gp", sentence: "Modern viral trends typically enjoy ephemeral success before fading from public interest." },
  { id: "w037", basic: "Eternal", intermediate: "Perpetual", word: "Immutable", category: "gp", sentence: "Basic human ethical principles ought to be viewed as immutable rights across cultures." },
  { id: "w038", basic: "Predictable", intermediate: "Foreseeable", word: "Inevitable", category: "gp", sentence: "Structural automation makes the transformation of traditional manufacturing jobs inevitable." },
  { id: "w039", basic: "Random", intermediate: "Arbitrary", word: "Capricious", category: "gp", sentence: "Regulatory policies that are too capricious discourage stable long-term foreign investment." },
  { id: "w040", basic: "Important", intermediate: "Crucial", word: "Paramount", category: "gp", sentence: "Public health safety must remain the paramount concern when approving new pharmaceutical products." },
  { id: "w041", basic: "Useless", intermediate: "Futile", word: "Ineffectual", category: "gp", sentence: "Symbolic policy statements prove ineffectual without concrete legislative funding." },
  { id: "w042", basic: "Bias", intermediate: "Partiality", word: "Partisanship", category: "gp", sentence: "Deepening political partisanship frequently stalls legislative progress in congress." },
  { id: "w043", basic: "Fairness", intermediate: "Equity", word: "Impartiality", category: "gp", sentence: "International judicial bodies rely on absolute impartiality to maintain global credibility." },
  { id: "w044", basic: "Freedom", intermediate: "Liberty", word: "Autonomy", category: "gp", sentence: "Higher education institutions demand institutional autonomy to pursue uninhibited scientific research." },
  { id: "w045", basic: "Control", intermediate: "Domination", word: "Hegemony", category: "gp", sentence: "Global tech platforms exert digital hegemony over international information flows." },
  { id: "w046", basic: "Rebellion", intermediate: "Defiance", word: "Insubordination", category: "gp", sentence: "Military hierarchy strictly disciplines any act of direct insubordination." },
  { id: "w047", basic: "Agreement", intermediate: "Consensus", word: "Unanimity", category: "gp", sentence: "Achieving complete unanimity among international partners on climate goals remains difficult." },
  { id: "w048", basic: "Argument", intermediate: "Dispute", word: "Polemic", category: "gp", sentence: "The author's latest book serves as a sharp polemic against modern corporate capitalism." },
  { id: "w049", basic: "Division", intermediate: "Separation", word: "Schism", category: "gp", sentence: "Divergent economic priorities caused a political schism among allied trade nations." },
  { id: "w050", basic: "Peak", intermediate: "Climax", word: "Zenith", category: "gp", sentence: "Historical records show the empire reached its cultural zenith during the golden century." },
  { id: "w051", basic: "Bottom", intermediate: "Low", word: "Nadir", category: "gp", sentence: "The country's diplomatic relations hit their nadir following the breach of international treaties." },
  { id: "w052", basic: "Support", intermediate: "Endorse", word: "Champion", category: "gp", sentence: "Dedicated policy groups champion environmental justice within marginalized communities." },
  { id: "w053", basic: "Attack", intermediate: "Criticize", word: "Denounce", category: "gp", sentence: "World leaders stepped forward to publicly denounce human rights violations." },
  { id: "w054", basic: "Forgive", intermediate: "Absolve", word: "Exonerate", category: "gp", sentence: "DNA testing evidence managed to fully exonerate the falsely accused individual." },
  { id: "w055", basic: "Blame", intermediate: "Implicate", word: "Incriminate", category: "gp", sentence: "Financial audit trails can incriminate corporate executives involved in fraud." },
  { id: "w056", basic: "Praise", intermediate: "Laud", word: "Exalt", category: "gp", sentence: "National propaganda campaigns often exalt historic victories to foster patriotism." },
  { id: "w057", basic: "Hate", intermediate: "Detest", word: "Abhor", category: "gp", sentence: "Civilized legal frameworks abhor the use of forced confessions in criminal proceedings." },
  { id: "w058", basic: "Ignore", intermediate: "Disregard", word: "Flout", category: "gp", sentence: "Corporations that flout safety laws must face significant structural penalties." },
  { id: "w059", basic: "Obey", intermediate: "Comply", word: "Acquiesce", category: "gp", sentence: "Citizens rarely acquiesce to authoritarian policies without domestic resistance over time." },
  { id: "w060", basic: "Refuse", intermediate: "Reject", word: "Repudiate", category: "gp", sentence: "Modern governments must formally repudiate historic colonial agreements." },
  { id: "w061", basic: "Accept", intermediate: "Embrace", word: "Sanction", category: "gp", sentence: "International bodies may sanction trade restrictions against law-breaking states." },
  { id: "w062", basic: "Demand", intermediate: "Require", word: "Mandate", category: "gp", sentence: "Constitutional law should mandate transparent elections across democratic states." },
  { id: "w063", basic: "Suggest", intermediate: "Propose", word: "Posit", category: "gp", sentence: "Economists posit that technological innovation drives long-term productivity gains." },
  { id: "w064", basic: "Claim", intermediate: "Assert", word: "Contend", category: "gp", sentence: "Legal analysts contend that existing copyright frameworks fail to address AI-generated content." },
  { id: "w065", basic: "Prove", intermediate: "Verify", word: "Corroborate", category: "gp", sentence: "Satellite imaging data helps corroborate news reports of environmental damage." },
  { id: "w066", basic: "Disprove", intermediate: "Refute", word: "Rebut", category: "gp", sentence: "Defense attorneys prepared extensive counter-evidence to rebut prosecution claims." },
  { id: "w067", basic: "Doubt", intermediate: "Question", word: "Query", category: "gp", sentence: "Independent auditors raised questions to query missing corporate financial records." },
  { id: "w068", basic: "Think", intermediate: "Ponder", word: "Cogitate", category: "gp", sentence: "Legal scholars must cogitate on the ethical boundaries of gene-editing technologies." },
  { id: "w069", basic: "Understand", intermediate: "Comprehend", word: "Fathom", category: "gp", sentence: "Researchers struggle to fathom the full scale of deep-sea ecological biodiversity." },
  { id: "w070", basic: "Remember", intermediate: "Recall", word: "Recollect", category: "gp", sentence: "Witnesses were asked to recollect specific details surrounding the emergency event." },
  { id: "w071", basic: "Notice", intermediate: "Perceive", word: "Discern", category: "gp", sentence: "Analytical models help data scientists discern underlying demographic shifts." },
  { id: "w072", basic: "Mislead", intermediate: "Deceive", word: "Beguile", category: "gp", sentence: "Marketing campaigns can beguile consumers into purchasing unnecessary products." },
  { id: "w073", basic: "Encourage", intermediate: "Foster", word: "Nurture", category: "gp", sentence: "Government grants help nurture promising green technology research projects." },
  { id: "w074", basic: "Discourage", intermediate: "Deter", word: "Inhibit", category: "gp", sentence: "Excessive taxation can inhibit technological research and market expansion." },
  { id: "w075", basic: "Exaggerate", intermediate: "Overstate", word: "Hyperbolize", category: "gp", sentence: "Media headlines tend to hyperbolize temporary economic downturns." },
  { id: "w076", basic: "Minimize", intermediate: "Downplay", word: "Trivialise", category: "gp", sentence: "Public discussions should not trivialise mental health issues among young demographics." },
  { id: "w077", basic: "Simplify", intermediate: "Streamline", word: "Distil", category: "gp", sentence: "Researchers must distil vast datasets into clear recommendations for policymakers." },
  { id: "w078", basic: "Complicate", intermediate: "Confuse", word: "Confound", category: "gp", sentence: "Unexpected economic variables can confound financial growth projections." },
  { id: "w079", basic: "Connect", intermediate: "Link", word: "Correlate", category: "gp", sentence: "Epidemiological studies correlate high urban pollution levels with respiratory illness." },
  { id: "w080", basic: "Separate", intermediate: "Isolate", word: "Segregate", category: "gp", sentence: "Historic city planning worked to segregate residential sectors by social class." },
  { id: "w081", basic: "Replace", intermediate: "Substitute", word: "Supersede", category: "gp", sentence: "Advanced satellite links will soon supersede traditional copper communications infrastructure." },
  { id: "w082", basic: "Restore", intermediate: "Renew", word: "Rejuvenate", category: "gp", sentence: "Urban investment plans aim to rejuvenate declining industrial zones." },
  { id: "w083", basic: "Create", intermediate: "Generate", word: "Instantiate", category: "gp", sentence: "Emerging smart cities instantiate modern sustainable architectural theory." },
  { id: "w084", basic: "Transform", intermediate: "Convert", word: "Transmute", category: "gp", sentence: "Efficient recycling facilities can transmute industrial waste into usable manufacturing fuel." },
  { id: "w085", basic: "Grow", intermediate: "Expand", word: "Proliferate", category: "gp", sentence: "Digital financial tools continue to proliferate across emerging global markets." },
  { id: "w086", basic: "Shrink", intermediate: "Diminish", word: "Dwindle", category: "gp", sentence: "Natural gas reserves continue to dwindle under intense global industrial demand." },
  { id: "w087", basic: "Rise", intermediate: "Ascend", word: "Surge", category: "gp", sentence: "International travel demand experiences a surge following peak holiday periods." },
  { id: "w088", basic: "Fall", intermediate: "Decline", word: "Plummet", category: "gp", sentence: "Stock valuations can plummet rapidly after unexpected regulatory announcements." },
  { id: "w089", basic: "Pass", intermediate: "Surpass", word: "Transcend", category: "gp", sentence: "Art and literature possess an inherent ability to transcend linguistic barriers." },
  { id: "w090", basic: "Stay", intermediate: "Remain", word: "Persist", category: "gp", sentence: "Systemic economic inequality can persist across generations without active social intervention." },
  { id: "w091", basic: "Waste", intermediate: "Squander", word: "Dissipate", category: "gp", sentence: "Misinformation scares tend to dissipate once official facts are confirmed." },
  { id: "w092", basic: "Save", intermediate: "Preserve", word: "Conserve", category: "gp", sentence: "Developing economies must conserve finite freshwater supplies to safeguard agriculture." },
  { id: "w093", basic: "Strict", intermediate: "Rigorous", word: "Draconian", category: "gp", sentence: "Civil liberties groups criticize draconian public surveillance legislation." },
  { id: "w094", basic: "Gentle", intermediate: "Mild", word: "Benign", category: "gp", sentence: "Certain automated algorithms play a benign role in organizing digital archives." },
  { id: "w095", basic: "Loud", intermediate: "Vocal", word: "Vociferous", category: "gp", sentence: "Consumer advocacy organizations have been vociferous in demanding product safety data." },
  { id: "w096", basic: "Quiet", intermediate: "Subdued", word: "Reticent", category: "gp", sentence: "Officials remained reticent regarding pending trade negotiation details." },
  { id: "w097", basic: "Avoid", intermediate: "Evade", word: "Eschew", category: "gp", sentence: "Ethical consumers increasingly eschew products linked to worker exploitation." },
  { id: "w098", basic: "Limit", intermediate: "Restrict", word: "Circumscribe", category: "gp", sentence: "Constitutional provisions serve to circumscribe state powers over private citizens." },
  { id: "w099", basic: "Combine", intermediate: "Merge", word: "Amalgamate", category: "gp", sentence: "Corporate mergers attempt to amalgamate logistics networks to reduce total costs." },
  { id: "w100", basic: "Improve", intermediate: "Enhance", word: "Ameliorate", category: "gp", sentence: "Direct policy aid can ameliorate immediate economic burdens for low-income citizens." },
  { id: "w101", basic: "Change", intermediate: "Modify", word: "Mutate", category: "gp", sentence: "Infectious viruses can mutate quickly, requiring redesigned medical vaccines." },
  { id: "w102", basic: "Deep", intermediate: "Profound", word: "Fathomless", category: "gp", sentence: "Deep ocean trenches remain vast environments with fathomless scientific mysteries." },
  { id: "w103", basic: "Shallow", intermediate: "Superficial", word: "Cursory", category: "gp", sentence: "A cursory reading of the proposal misses key environmental regulatory details." },
  { id: "w104", basic: "Broad", intermediate: "Comprehensive", word: "All-encompassing", category: "gp", sentence: "The new policy framework presents an all-encompassing strategy for clean energy transition." },
  { id: "w105", basic: "Narrow", intermediate: "Parochial", word: "Provincial", category: "gp", sentence: "Isolating trade policies reflects a provincial view of global economic interconnectedness." },
  { id: "w106", basic: "Sharp", intermediate: "Acute", word: "Incisive", category: "gp", sentence: "The journalist's incisive questioning exposed major policy contradictions during the debate." },
  { id: "w107", basic: "Dull", intermediate: "Monotonous", word: "Pedestrian", category: "gp", sentence: "Analysts dismissed the theoretical paper as a pedestrian retread of existing literature." },
  { id: "w108", basic: "Active", intermediate: "Energetic", word: "Vibrant", category: "gp", sentence: "Urban centers benefit economically from having a vibrant arts and media culture." },
  { id: "w109", basic: "Passive", intermediate: "Inactive", word: "Quiescent", category: "gp", sentence: "Volcanoes can remain quiescent for centuries before experiencing sudden eruptions." },
  { id: "w110", basic: "Stubborn", intermediate: "Obstinate", word: "Intransigent", category: "gp", sentence: "Negotiations stalled because both political parties remained completely intransigent." },
  { id: "w111", basic: "Flexible", intermediate: "Adaptable", word: "Malleable", category: "gp", sentence: "Young minds are exceptionally malleable, making early education quality critical." },
  { id: "w112", basic: "Friendly", intermediate: "Amicable", word: "Convivial", category: "gp", sentence: "International diplomatic summits benefit from a convivial negotiating atmosphere." },
  { id: "w113", basic: "Hostile", intermediate: "Antagonistic", word: "Bellicose", category: "gp", sentence: "The foreign minister's bellicose rhetoric escalated border tensions sharply." },
  { id: "w114", basic: "Honest", intermediate: "Candor", word: "Veracious", category: "gp", sentence: "Investigative reporting must rely exclusively on veracious eyewitness testimonies." },
  { id: "w115", basic: "Sly", intermediate: "Deceitful", word: "Disingenuous", category: "gp", sentence: "It is disingenuous to argue that economic growth proceeds without environmental costs." },
  { id: "w116", basic: "Proud", intermediate: "Arrogant", word: "Supercilious", category: "gp", sentence: "The executive's supercilious attitude toward critics damaged company PR efforts." },
  { id: "w117", basic: "Humble", intermediate: "Modest", word: "Unpretentious", category: "gp", sentence: "The leader's unpretentious communication style resonated deeply with working-class voters." },
  { id: "w118", basic: "Generous", intermediate: "Magnanimous", word: "Altruistic", category: "gp", sentence: "Philanthropic institutions fund global disease eradication through altruistic initiatives." },
  { id: "w119", basic: "Greedy", intermediate: "Avaricious", word: "Acquisitive", category: "gp", sentence: "Unchecked corporate expansion reflects an acquisitive mindset focused on market dominance." },
  { id: "w120", basic: "Brave", intermediate: "Intrepid", word: "Audacious", category: "gp", sentence: "The startup launched an audacious plan to capture space satellite communications market share." },
  { id: "w121", basic: "Timid", intermediate: "Fearful", word: "Pusillanimous", category: "gp", sentence: "Critics condemned the state's pusillanimous failure to confront systemic corporate corruption." },
  { id: "w122", basic: "Wisdom", intermediate: "Sagacity", word: "Erudition", category: "gp", sentence: "The law professor demonstrated profound historical erudition during the constitutional lecture." },
  { id: "w123", basic: "Folly", intermediate: "Foolishness", word: "Fatuity", category: "gp", sentence: "Policy commentators pointed out the absolute fatuity of cutting education funding to save costs." },
  { id: "w124", basic: "Truth", intermediate: "Veracity", word: "Verity", category: "gp", sentence: "Historical research relies on empirical facts to confirm the verity of official state records." },
  { id: "w125", basic: "Lie", intermediate: "Falsehood", word: "Prevarication", category: "gp", sentence: "Spokespersons who resort to prevarication quickly lose public credibility." },
  { id: "w126", basic: "Peace", intermediate: "Tranquility", word: "Serenity", category: "gp", sentence: "Green national parks offer urban populations necessary spaces of natural serenity." },
  { id: "w127", basic: "Chaos", intermediate: "Turmoil", word: "Pandemonium", category: "gp", sentence: "Financial trading floors erupted into complete pandemonium following the bank crash news." },
  { id: "w128", basic: "Wealth", intermediate: "Prosperity", word: "Opulence", category: "gp", sentence: "Excessive architectural opulence often stands in stark contrast to surrounding urban poverty." },
  { id: "w129", basic: "Poverty", intermediate: "Indigence", word: "Penury", category: "gp", sentence: "Developing regions require international aid to lift rural farming families out of severe penury." },
  { id: "w130", basic: "Order", intermediate: "Hierarchy", word: "Systematization", category: "gp", sentence: "Industrial operations depend on the precise systematization of manufacturing steps." },
  { id: "w131", basic: "Disregard", intermediate: "Neglect", word: "Dereliction", category: "gp", sentence: "Failing to maintain critical bridge infrastructure represents a gross dereliction of civic duty." },
  { id: "w132", basic: "Loyalty", intermediate: "Fidelity", word: "Allegiance", category: "gp", sentence: "Citizens hold dual civic allegiance to local regional communities and the national government." },
  { id: "w133", basic: "Betrayal", intermediate: "Treachery", word: "Perfidy", category: "gp", sentence: "Spying scandal revelations exposed internal perfidy within foreign intelligence agencies." },
  { id: "w134", basic: "Skill", intermediate: "Expertise", word: "Adroitness", category: "gp", sentence: "Negotiators handled delicate diplomatic talks with remarkable strategic adroitness." },
  { id: "w135", basic: "Clumsiness", intermediate: "Ineptitude", word: "Maladroitness", category: "gp", sentence: "Strategic maladroitness by trade representatives led to canceled international agreements." },
  { id: "w136", basic: "Beauty", intermediate: "Aesthetics", word: "Resplendence", category: "gp", sentence: "Historical cultural artifacts displayed incredible artistic resplendence in national museums." },
  { id: "w137", basic: "Ugliness", intermediate: "Unattractiveness", word: "Hideousness", category: "gp", sentence: "Industrial pollution runoff highlights the raw ecological hideousness of unchecked production." },
  { id: "w138", basic: "Clean", intermediate: "Pristine", word: "Immaculate", category: "gp", sentence: "Modern chip fabrication cleanrooms require immaculate operating environments to prevent defects." },
  { id: "w139", basic: "Dirty", intermediate: "Sullied", word: "Squalid", category: "gp", sentence: "Rapid urbanization without housing infrastructure creates squalid living conditions in informal settlements." },
  { id: "w140", basic: "Permanent", intermediate: "Indelible", word: "Irrevocable", category: "gp", sentence: "Executive pardon signatures carry irrevocable legal power within the constitutional system." },
  { id: "w141", basic: "Variable", intermediate: "Fluctuating", word: "Protean", category: "gp", sentence: "The protean nature of digital threats requires flexible defensive cyber software frameworks." },
  { id: "w142", basic: "Similar", intermediate: "Analogous", word: "Homogeneous", category: "gp", sentence: "Globalized consumer platforms risk turning distinct local cultures into a homogeneous mass media format." },
  { id: "w143", basic: "Diverse", intermediate: "Eclectic", word: "Heterogeneous", category: "gp", sentence: "Modern metropolis populations comprise highly heterogeneous social and linguistic backgrounds." },
  { id: "w144", basic: "Central", intermediate: "Pivotal", word: "Focal", category: "gp", sentence: "Reducing carbon emissions forms the focal objective of global climate agreements." },
  { id: "w145", basic: "Peripheral", intermediate: "Marginal", word: "Tangential", category: "gp", sentence: "Debate participants should avoid bringing up tangential topics that derail core legislative discussions." },
  { id: "w146", basic: "Essential", intermediate: "Indispensable", word: "Integral", category: "gp", sentence: "Ethical considerations must remain integral to advanced biotechnology research protocols." },
  { id: "w147", basic: "Extra", intermediate: "Superfluous", word: "Redundant", category: "gp", sentence: "Automated administrative processes render manual paperwork data entry completely redundant." },
  { id: "w148", basic: "Direct", intermediate: "Forthright", word: "Unambiguous", category: "gp", sentence: "Statutory regulations must provide unambiguous instructions to avoid legal misinterpretation." },
  { id: "w149", basic: "Indirect", intermediate: "Circuitous", word: "Oblique", category: "gp", sentence: "The report made oblique references to corporate mismanagement without naming specific executives." },
  { id: "w150", basic: "Urgent", intermediate: "Imperative", word: "Exigent", category: "gp", sentence: "Disasters require exigent crisis response measures to maintain essential public utility services." },
  { id: "w151", basic: "Trivial", intermediate: "Insignificant", word: "Trifling", category: "gp", sentence: "Legal systems should not waste public resources settling trifling private disputes." },
  { id: "w152", basic: "Excessive", intermediate: "Extravagant", word: "Immoderate", category: "gp", sentence: "Uncontrolled capital spending leads to immoderate debt burdens for municipal governments." },
  { id: "w153", basic: "Moderate", intermediate: "Temperate", word: "Abstemious", category: "gp", sentence: "Financial institutions recommend abstemious borrowing practices during unpredictable market cycles." },
  { id: "w154", basic: "Exact", intermediate: "Meticulous", word: "Scrupulous", category: "gp", sentence: "Clinical trial teams must maintain scrupulous records to meet health regulation standards." },
  { id: "w155", basic: "Vague", intermediate: "Ambiguous", word: "Equivocal", category: "gp", sentence: "Survey results yielded equivocal conclusions regarding consumer preference changes." },
  { id: "w156", basic: "Certain", intermediate: "Incontrovertible", word: "Indubitable", category: "gp", sentence: "Forensic science evidence provided indubitable proof of the suspect's involvement." },
  { id: "w157", basic: "Questionable", intermediate: "Dubious", word: "Equivocal", category: "gp", sentence: "Political speeches containing equivocal language frustrate voters seeking firm promises." },
  { id: "w158", basic: "Obvious", intermediate: "Self-evident", word: "Axiomatic", category: "gp", sentence: "It is axiomatic that equal access to education drives broader economic mobility." },
  { id: "w159", basic: "Mysterious", intermediate: "Enigmatic", word: "Arcane", category: "gp", sentence: "Understanding legacy code requires navigating arcane technical software documentation." },
  { id: "w160", basic: "Common", intermediate: "Widespread", word: "Ubiquitous", category: "gp", sentence: "Smartphones have transformed from luxury items into ubiquitous daily necessities globally." },
  { id: "w161", basic: "Rare", intermediate: "Infrequent", word: "Sporadic", category: "gp", sentence: "Wireless network access in remote mountainous areas remains sporadic at best." },
  { id: "w162", basic: "Modern", intermediate: "Contemporary", word: "Cutting-edge", category: "gp", sentence: "Medical research centers require cutting-edge equipment to innovate life-saving treatments." },
  { id: "w163", basic: "Ancient", intermediate: "Archaic", word: "Primeval", category: "gp", sentence: "Protected nature reserves shield primeval rainforest environments from commercial logging operations." },
  { id: "w164", basic: "Foreign", intermediate: "Alien", word: "Exogenous", category: "gp", sentence: "Local markets experienced economic volatility caused by exogenous global energy shocks." },
  { id: "w165", basic: "Local", intermediate: "Indigenous", word: "Endemic", category: "gp", sentence: "Dengue fever remains endemic across tropical regions during seasonal rainfall periods." },
  { id: "w166", basic: "Main", intermediate: "Primary", word: "Predominant", category: "gp", sentence: "Agriculture continues to be the predominant industry driving regional rural economies." },
  { id: "w167", basic: "Secondary", intermediate: "Subordinate", word: "Ancillary", category: "gp", sentence: "Logistics services provide ancillary support essential to the primary manufacturing sector." },
  { id: "w168", basic: "Harm", intermediate: "Detriment", word: "Deleteriousness", category: "gp", sentence: "Environmental impact assessments highlight the deleteriousness of chemical ocean dumping." },
  { id: "w169", basic: "Benefit", intermediate: "Advantage", word: "Utility", category: "gp", sentence: "Renewable energy installations demonstrate immense practical utility in reducing national carbon emissions." },
  { id: "w170", basic: "Agreement", intermediate: "Accord", word: "Concordance", category: "gp", sentence: "Successful treaties reflect absolute diplomatic concordance across all negotiating parties." },
  { id: "w171", basic: "Conflict", intermediate: "Friction", word: "Dissonance", category: "gp", sentence: "A stark cognitive dissonance exists between sustainability pledges and corporate spending realities." },
  { id: "w172", basic: "Victory", intermediate: "Triumph", word: "Ascendancy", category: "gp", sentence: "Digital commerce platforms established market ascendancy over traditional brick-and-mortar stores." },
  { id: "w173", basic: "Defeat", intermediate: "Overthrow", word: "Subversion", category: "gp", sentence: "Foreign propaganda campaigns often aim at the political subversion of democratic elections." },
  { id: "w174", basic: "Growth", intermediate: "Expansion", word: "Augmentation", category: "gp", sentence: "Automation aims at human worker capability augmentation, rather than complete job replacement." },
  { id: "w175", basic: "Loss", intermediate: "Deprivation", word: "Attrition", category: "gp", sentence: "Combat zones experience steady resource attrition as long-term conflicts persist over years." },
  { id: "w176", basic: "Origin", intermediate: "Genesis", word: "Provenance", category: "gp", sentence: "Art historians trace the precise provenance of ancient artifacts before museum display." },
  { id: "w177", basic: "End", intermediate: "Termination", word: "Cessation", category: "gp", sentence: "Treaties require an immediate cessation of military hostilities along disputed border lines." },
  { id: "w178", basic: "Danger", intermediate: "Jeopardy", word: "Peril", category: "gp", sentence: "Coastal regions face severe ecological peril as sea levels rise over the coming decades." },
  { id: "w179", basic: "Safety", intermediate: "Protection", word: "Sanctuary", category: "gp", sentence: "Marine protected reserves offer essential sanctuary for endangered coral reef species." },
  { id: "w180", basic: "Force", intermediate: "Coercion", word: "Duress", category: "gp", sentence: "Contracts signed under political duress are legally invalid in international courts." },
  { id: "w181", basic: "Choice", intermediate: "Volition", word: "Discretion", category: "gp", sentence: "Judges hold absolute legal discretion when sentencing offenders within statutory limits." },
  { id: "w182", basic: "Duty", intermediate: "Obligation", word: "Imperative", category: "gp", sentence: "Environmental sustainability has become an economic imperative for forward-thinking corporations." },
  { id: "w183", basic: "Right", intermediate: "Entitlement", word: "Prerogative", category: "gp", sentence: "Executive pardons remain the constitutional prerogative of state heads." },
  { id: "w184", basic: "Policy", intermediate: "Doctrine", word: "Tenet", category: "gp", sentence: "Secular governance maintains the essential tenet of separating religious doctrine from law." },
  { id: "w185", basic: "Rule", intermediate: "Mandate", word: "Precept", category: "gp", sentence: "Rule of law serves as a foundational precept for all democratic legal systems." },
  { id: "w186", basic: "Leader", intermediate: "Figurehead", word: "Lynchpin", category: "gp", sentence: "Semiconductor manufacturing acts as the critical technological lynchpin of the modern global economy." },
  { id: "w187", basic: "Follower", intermediate: "Adherent", word: "Acolyte", category: "gp", sentence: "The political candidate drew dedicated support from every loyal campaign acolyte." },
  { id: "w188", basic: "Crowd", intermediate: "Multitude", word: "Horde", category: "gp", sentence: "Public transit stations must handle a vast horde of commuters during peak urban rush hours." },
  { id: "w189", basic: "Solitude", intermediate: "Isolation", word: "Seclusion", category: "gp", sentence: "Academic retreat centers offer quiet seclusion conducive to intensive literary research." },
  { id: "w190", basic: "Speech", intermediate: "Rhetoric", word: "Discourse", category: "gp", sentence: "Respectful public discourse remains essential for healthy democratic decision-making processes." },
  { id: "w191", basic: "Silence", intermediate: "Taciturnity", word: "Reticence", category: "gp", sentence: "The witness showed extreme reticence when questioned about institutional corruption." },
  { id: "w192", basic: "Vision", intermediate: "Foresight", word: "Prescience", category: "gp", sentence: "The analyst's early writings displayed remarkable prescience regarding the modern digital shift." },
  { id: "w193", basic: "Blindness", intermediate: "Ignorance", word: "Myopia", category: "gp", sentence: "Short-sighted economic myopia leads politicians to neglect long-term infrastructure investment." },
  { id: "w194", basic: "Modernity", intermediate: "Advancement", word: "Contemporary State", category: "gp", sentence: "The contemporary state of automated manufacturing relies heavily on robotics and machine learning." },
  { id: "w195", basic: "Tradition", intermediate: "Heritage", word: "Customary Practice", category: "gp", sentence: "Agricultural communities rely on customary practice passed down across generations." },
  { id: "w196", basic: "Trend", intermediate: "Phenomenon", word: "Zeitgeist", category: "gp", sentence: "Capturing the cultural zeitgeist is essential for successful global advertising campaigns." },
  { id: "w197", basic: "Outcast", intermediate: "Pariah", word: "Ostracized Individual", category: "gp", sentence: "Whistleblowers often face life as an ostracized individual within their former industries." },
  { id: "w198", basic: "Master", intermediate: "Paragon", word: "Exemplar", category: "gp", sentence: "The renewable energy company serves as an operational exemplar for corporate green transition." },
  { id: "w199", basic: "Copy", intermediate: "Replica", word: "Simulacrum", category: "gp", sentence: "Virtual reality software creates a digital simulacrum of real-world training environments." },
  { id: "w200", basic: "Opposite", intermediate: "Inverse", word: "Antithesis", category: "gp", sentence: "Monopolistic market control represents the absolute antithesis of free market competition." },
  { id: "w201", basic: "Harmless", intermediate: "Safe", word: "Innocuous", category: "gp", sentence: "What seemed like an innocuous comment about the recipe turned into an argument over dinner." },
  { id: "w202", basic: "Harmful", intermediate: "Damaging", word: "Noxious", category: "gp", sentence: "Leaving the damp laundry in the gym bag overnight created a noxious smell by morning." },
  { id: "w203", basic: "Unavoidable", intermediate: "Certain", word: "Ineluctable", category: "gp", sentence: "Getting tired after running a marathon is an ineluctable part of the recovery process." },
  { id: "w204", basic: "Unchanging", intermediate: "Fixed", word: "Immutable", category: "gp", sentence: "Her morning routine of drinking black coffee before checking emails remained completely immutable." },
  { id: "w205", basic: "Changing", intermediate: "Variable", word: "Protean", category: "gp", sentence: "His musical style is protean, shifting easily from classical piano to modern digital beats." },
  { id: "w206", basic: "Short-lived", intermediate: "Brief", word: "Transient", category: "gp", sentence: "The joy of winning a single video game match is often transient, fading after a few minutes." },
  { id: "w207", basic: "Long-lasting", intermediate: "Permanent", word: "Abiding", category: "gp", sentence: "She has maintained an abiding passion for photography ever since her grandfather gave her an old camera." },
  { id: "w208", basic: "Unclear", intermediate: "Confusing", word: "Obscurantist", category: "gp", sentence: "The user manual was written in such obscurantist technical jargon that nobody could assemble the bookshelf." },
  { id: "w209", basic: "Clear", intermediate: "Obvious", word: "Perspicuous", category: "gp", sentence: "The coach gave a perspicuous explanation of the game plan, so every player knew their exact role." },
  { id: "w210", basic: "Mysterious", intermediate: "Secret", word: "Recondite", category: "gp", sentence: "The professor spent hours discussing recondite details of ancient pottery that only a few specialists understood." },
  { id: "w211", basic: "Commonplace", intermediate: "Everyday", word: "Quotidian", category: "gp", sentence: "Washing dishes and making the bed are among the quotidian chores that keep a household running." },
  { id: "w212", basic: "Excessive", intermediate: "Over-the-top", word: "Inordinate", category: "gp", sentence: "He spent an inordinate amount of time customizing his character\'s outfit instead of playing the main story." },
  { id: "w213", basic: "Moderate", intermediate: "Balanced", word: "Temperate", category: "gp", sentence: "Maintaining a temperate exercise routine helps prevent injuries while building long-term fitness." },
  { id: "w214", basic: "Carefree", intermediate: "Unconcerned", word: "Nonchalant", category: "gp", sentence: "She shrugged with a nonchalant smile when her ice cream dropped, acting like it did not bother her at all." },
  { id: "w215", basic: "Careful", intermediate: "Thorough", word: "Fastidious", category: "gp", sentence: "He is fastidious about keeping his workspace organized, placing every pen in its designated holder." },
  { id: "w216", basic: "Rash", intermediate: "Impulsive", word: "Impetuous", category: "gp", sentence: "Making an impetuous purchase online usually leads to regret when the monthly statement arrives." },
  { id: "w217", basic: "Cautious", intermediate: "Guarded", word: "Circumspect", category: "gp", sentence: "Be circumspect when sharing personal passwords, even with close friends or colleagues." },
  { id: "w218", basic: "Friendly", intermediate: "Welcoming", word: "Affable", category: "gp", sentence: "The barista\'s affable personality always puts customers in a good mood first thing in the morning." },
  { id: "w219", basic: "Aggressive", intermediate: "Hostile", word: "Pugnacious", category: "gp", sentence: "The dog became surprisingly pugnacious whenever anyone tried to take away its favorite chew toy." },
  { id: "w220", basic: "Arrogant", intermediate: "Haughty", word: "Imperious", category: "gp", sentence: "The head chef used an imperious tone when commanding the kitchen staff during the dinner rush." },
  { id: "w221", basic: "Humble", intermediate: "Modest", word: "Self-effacing", category: "gp", sentence: "Despite winning first place in the art competition, she gave a self-effacing response, praising the other artists." },
  { id: "w222", basic: "Generous", intermediate: "Giving", word: "Beneficent", category: "gp", sentence: "A beneficent neighbor offered to watch our dog and water our garden while we were away on holiday." },
  { id: "w223", basic: "Stingy", intermediate: "Ungenerous", word: "Parsimonious", category: "gp", sentence: "He was so parsimonious with his savings that he refused to replace his shoes even after the soles wore out." },
  { id: "w224", basic: "Stubborn", intermediate: "Unyielding", word: "Recalcitrant", category: "gp", sentence: "The recalcitrant toddler sat on the floor and refused to put on his shoes for school." },
  { id: "w225", basic: "Obedient", intermediate: "Compliant", word: "Obsequious", category: "gp", sentence: "The server\'s obsequious behavior, constantly wiping down the table and nodding, made the diners feel uncomfortable." },
  { id: "w226", basic: "Outspoken", intermediate: "Expressive", word: "Garrulous", category: "gp", sentence: "The garrulous driver chatted non-stop about his personal life during the entire hour-long ride to the airport." },
  { id: "w227", basic: "Silent", intermediate: "Uncommunicative", word: "Incommunicative", category: "gp", sentence: "After losing the championship match, the tennis player remained incommunicative in the locker room." },
  { id: "w228", basic: "Sad", intermediate: "Gloomy", word: "Lugubrious", category: "gp", sentence: "A lugubrious mood hung over the room after the final episode of the beloved TV drama ended on a sad note." },
  { id: "w229", basic: "Happy", intermediate: "Joyful", word: "Ebullient", category: "gp", sentence: "The children were in an ebullient mood on the last day of school, cheering as they ran out the doors." },
  { id: "w230", basic: "Irritable", intermediate: "Bad-tempered", word: "Fractious", category: "gp", sentence: "The kids grew fractious after sitting in the back seat during the five-hour road trip." },
  { id: "w231", basic: "Calm", intermediate: "Peaceful", word: "Placid", category: "gp", sentence: "Looking out over the placid lake on a windless morning brought a deep sense of peace." },
  { id: "w232", basic: "Active", intermediate: "Energetic", word: "Vigorous", category: "gp", sentence: "Taking a vigorous walk every morning is a great way to boost your energy levels for the day." },
  { id: "w233", basic: "Lazy", intermediate: "Idle", word: "Indolent", category: "gp", sentence: "On lazy Sundays, he preferred an indolent afternoon of lying on the couch reading graphic novels." },
  { id: "w234", basic: "Clever", intermediate: "Intelligent", word: "Perspicacious", category: "gp", sentence: "The perspicacious detective noticed a tiny muddy footprint that everyone else had walked past." },
  { id: "w235", basic: "Foolish", intermediate: "Stupid", word: "Inane", category: "gp", sentence: "Instead of discussing the plot of the movie, they spent half an hour making inane jokes about the extra\'s haircut." },
  { id: "w236", basic: "Brave", intermediate: "Fearless", word: "Dauntless", category: "gp", sentence: "The dauntless hiker pushed through the sudden rainstorm to reach the summit before sunset." },
  { id: "w237", basic: "Cowardly", intermediate: "Fearful", word: "Craven", category: "gp", sentence: "Running away and leaving your teammate to clean up the mess was a craven thing to do." },
  { id: "w238", basic: "Truthful", intermediate: "Honest", word: "Veritable", category: "gp", sentence: "The dessert buffet was a veritable paradise for anyone with a sweet tooth." },
  { id: "w239", basic: "Deceitful", intermediate: "Dishonest", word: "Mendacious", category: "gp", sentence: "Reviewers caught the seller making mendacious claims about the product\'s durability online." },
  { id: "w240", basic: "Loyalty", intermediate: "Faithfulness", word: "Fealty", category: "gp", sentence: "The gaming squad swore absolute fealty to their team captain during the online tournament." },
  { id: "w241", basic: "Treason", intermediate: "Betrayal", word: "Treachery", category: "gp", sentence: "Leaking the surprise party details to the birthday boy was viewed as a minor treachery by his siblings." },
  { id: "w242", basic: "Freedom", intermediate: "Independence", word: "Sovereignty", category: "gp", sentence: "Having complete sovereignty over your own daily schedule is one of the best parts of working freelance." },
  { id: "w243", basic: "Slavery", intermediate: "Bondage", word: "Servitude", category: "gp", sentence: "Feeling trapped in a job with endless overtime can start to feel like daily servitude." },
  { id: "w244", basic: "Harmony", intermediate: "Agreement", word: "Concord", category: "gp", sentence: "After hours of negotiating who gets which room, the roommates finally reached a peaceful concord." },
  { id: "w245", basic: "Conflict", intermediate: "Disagreement", word: "Discord", category: "gp", sentence: "Trying to choose a restaurant for a group of ten people often causes unnecessary discord." },
  { id: "w246", basic: "Disaster", intermediate: "Catastrophe", word: "Calamity", category: "gp", sentence: "Forgetting to save the file right before the laptop died felt like a major calamity." },
  { id: "w247", basic: "Success", intermediate: "Achievement", word: "Accomplishment", category: "gp", sentence: "Finishing a 1,000-piece puzzle after three weeks gave her a huge sense of accomplishment." },
  { id: "w248", basic: "Failure", intermediate: "Collapse", word: "Fiasco", category: "gp", sentence: "The attempt to bake a three-tier birthday cake ended in a total fiasco when the top layer slid off." },
  { id: "w249", basic: "Chaos", intermediate: "Confusion", word: "Turmoil", category: "gp", sentence: "The sudden announcement that the flight was canceled caused immediate turmoil at the gate." },
  { id: "w250", basic: "Order", intermediate: "Arrangement", word: "Organization", category: "gp", sentence: "Good kitchen organization makes cooking dinner much faster and far less stressful." },
  { id: "w251", basic: "Wealth", intermediate: "Riches", word: "Prosperity", category: "gp", sentence: "Hard work and smart budgeting led to years of steady financial prosperity for the family business." },
  { id: "w252", basic: "Poverty", intermediate: "Hardship", word: "Destitution", category: "gp", sentence: "Losing all his gear in the game left his character in a state of virtual destitution." },
  { id: "w253", basic: "Skill", intermediate: "Ability", word: "Proficiency", category: "gp", sentence: "Practice every evening allowed her to reach high proficiency in playing the acoustic guitar." },
  { id: "w254", basic: "Incompetence", intermediate: "Lack of skill", word: "Inadequacy", category: "gp", sentence: "Feeling a sense of inadequacy when starting a complex new hobby is completely normal." },
  { id: "w255", basic: "Charm", intermediate: "Attraction", word: "Allure", category: "gp", sentence: "The allure of sleeping in on a rainy Saturday morning is almost impossible to resist." },
  { id: "w256", basic: "Disgust", intermediate: "Aversion", word: "Repulsion", category: "gp", sentence: "He felt a strong wave of repulsion when he opened the fridge and smelled the spoiled milk." },
  { id: "w257", basic: "Purity", intermediate: "Cleanliness", word: "Unblemished State", category: "gp", sentence: "Collecting vintage comic books means trying to keep them in their unblemished state." },
  { id: "w258", basic: "Contamination", intermediate: "Pollution", word: "Vitiation", category: "gp", sentence: "Adding salt instead of sugar led to the complete vitiation of the cake batter." },
  { id: "w259", basic: "Leader", intermediate: "Head", word: "Hegemon", category: "gp", sentence: "In the board game, whoever controls the central trade route becomes the unchallenged hegemon." },
  { id: "w260", basic: "Subordinate", intermediate: "Inferior", word: "Underling", category: "gp", sentence: "The office manager sent an underling to pick up coffee orders for the whole team." },
  { id: "w261", basic: "Crowd", intermediate: "Gathering", word: "Congregation", category: "gp", sentence: "A large congregation of fans waited outside the hotel hoping to get an autograph from the actor." },
  { id: "w262", basic: "Solitude", intermediate: "Isolation", word: "Loneliness", category: "gp", sentence: "Moving to a new city without knowing anyone can bring a temporary feeling of loneliness." },
  { id: "w263", basic: "Speech", intermediate: "Talk", word: "Address", category: "gp", sentence: "The principal gave a short welcome address to the incoming students on their first morning." },
  { id: "w264", basic: "Silence", intermediate: "Stillness", word: "Quiescence", category: "gp", sentence: "After hours of non-stop barking, the neighborhood dogs finally settled into a peaceful quiescence." },
  { id: "w265", basic: "Foresight", intermediate: "Planning", word: "Prognostication", category: "gp", sentence: "Making an accurate prognostication about who will win the championship is tough before the season starts." },
  { id: "w266", basic: "Ignorance", intermediate: "Unawareness", word: "Unacquaintance", category: "gp", sentence: "Her complete unacquaintance with basic coding made the introductory computer class challenging." },
  { id: "w267", basic: "Tradition", intermediate: "Heritage", word: "Custom", category: "gp", sentence: "It is a family custom to gather at grandma\'s house for a big Sunday brunch every weekend." },
  { id: "w268", basic: "Innovation", intermediate: "Invention", word: "Novelty", category: "gp", sentence: "The novelty of the new video game console wore off after two weeks of playing it every night." },
  { id: "w269", basic: "Example", intermediate: "Model", word: "Archetype", category: "gp", sentence: "The wise old mentor character is a classic archetype found in almost every fantasy novel." },
  { id: "w270", basic: "Fake", intermediate: "Imitation", word: "Counterfeit", category: "gp", sentence: "Be careful when buying designer sneakers online, as many cheap listings turn out to be counterfeit." },
  { id: "w271", basic: "Opposite", intermediate: "Reverse", word: "Antipode", category: "gp", sentence: "Living in a cluttered room is the exact antipode of minimal home design." },
  { id: "w272", basic: "Cause", intermediate: "Reason", word: "Antecedent", category: "gp", sentence: "A heavy night of studying was the clear antecedent to her high score on the final exam." },
  { id: "w273", basic: "Effect", intermediate: "Result", word: "Sequelae", category: "gp", sentence: "Sore muscles and tired legs are the natural sequelae of completing a ten-mile hike." },
  { id: "w274", basic: "Burden", intermediate: "Weight", word: "Onus", category: "gp", sentence: "The onus is on the player who spilled the drink to wipe up the board game table." },
  { id: "w275", basic: "Relief", intermediate: "Ease", word: "Alleviation", category: "gp", sentence: "Applying an ice pack provided instant alleviation from the pain of a sprained ankle." },
  { id: "w276", basic: "Threat", intermediate: "Hazard", word: "Imminence", category: "gp", sentence: "The dark storm clouds gathering overhead highlighted the imminence of a heavy downpour." },
  { id: "w277", basic: "Protection", intermediate: "Defense", word: "Bulwark", category: "gp", sentence: "A good night\'s sleep acts as a primary bulwark against catching a common cold." },
  { id: "w278", basic: "Force", intermediate: "Compulsion", word: "Constraint", category: "gp", sentence: "Budget constraints meant they had to plan a road trip closer to home this summer." },
  { id: "w279", basic: "Choice", intermediate: "Option", word: "Alternative", category: "gp", sentence: "Taking the subway proved to be a faster alternative to driving through city traffic." },
  { id: "w280", basic: "Rule", intermediate: "Regulation", word: "Statute", category: "gp", sentence: "The community gym posted a strict statute forbidding glass bottles near the swimming pool." },
  { id: "w281", basic: "Standard", intermediate: "Norm", word: "Criterion", category: "gp", sentence: "Taste is the single most important criterion when judging a cooking contest." },
  { id: "w282", basic: "Exception", intermediate: "Irregularity", word: "Anomaly", category: "gp", sentence: "Finding a sunny day during the peak of the rainy season was a pleasant anomaly." },
  { id: "w283", basic: "Surplus", intermediate: "Excess", word: "Surfeit", category: "gp", sentence: "Having a surfeit of leftovers meant no one needed to cook dinner for three straight days." },
  { id: "w284", basic: "Shortage", intermediate: "Lack", word: "Deficit", category: "gp", sentence: "Skipping sleep for three nights created a massive sleep deficit that took a whole weekend to fix." },
  { id: "w285", basic: "Vitality", intermediate: "Energy", word: "Animation", category: "gp", sentence: "The children\'s faces lit up with animation as soon as the magician began his performance." },
  { id: "w286", basic: "Weakness", intermediate: "Frailty", word: "Feebleness", category: "gp", sentence: "Recovering from the flu left her with a temporary feebleness that made climbing stairs tough." },
  { id: "w287", basic: "Passion", intermediate: "Enthusiasm", word: "Ardor", category: "gp", sentence: "He practiced his skateboard tricks with absolute ardor, trying again and again until he landed them." },
  { id: "w288", basic: "Indifference", intermediate: "Unconcern", word: "Disinterest", category: "gp", sentence: "The cat watched the rolling ball with complete disinterest before slowly closing its eyes." },
  { id: "w289", basic: "Pride", intermediate: "Self-importance", word: "Arrogance", category: "gp", sentence: "Assuming you will win without practicing shows a level of arrogance that usually leads to losing." },
  { id: "w290", basic: "Humility", intermediate: "Modesty", word: "Meekness", category: "gp", sentence: "His quiet meekness made people mistake him for being shy, though he was just thoughtful." },
  { id: "w291", basic: "Kindness", intermediate: "Goodwill", word: "Altruism", category: "gp", sentence: "Paying for the stranger\'s coffee behind you in line is a simple act of altruism." },
  { id: "w292", basic: "Malice", intermediate: "Spite", word: "Malevolence", category: "gp", sentence: "The movie villain\'s subtle malevolence was clear from his eerie, silent stare." },
  { id: "w293", basic: "Openness", intermediate: "Honesty", word: "Directness", category: "gp", sentence: "I appreciate the coach\'s directness when explaining where I need to improve my technique." },
  { id: "w294", basic: "Secrecy", intermediate: "Concealment", word: "Furtiveness", category: "gp", sentence: "The cat moved across the kitchen counter with quiet furtiveness, targeting the unattended chicken." },
  { id: "w295", basic: "Change", intermediate: "Modification", word: "Transformation", category: "gp", sentence: "Remodeling the old basement resulted in a complete transformation into a cozy movie room." },
  { id: "w296", basic: "Stability", intermediate: "Permanence", word: "Stasis", category: "gp", sentence: "Staying in a routine without trying new activities can leave your personal growth in a state of stasis." },
  { id: "w297", basic: "Rise", intermediate: "Increase", word: "Escalation", category: "gp", sentence: "A minor disagreement over house rules quickly turned into a major escalation between the roommates." },
  { id: "w298", basic: "Fall", intermediate: "Decrease", word: "Abatement", category: "gp", sentence: "The sudden abatement of the loud wind made it possible to hear the birds singing outside." },
  { id: "w299", basic: "Growth", intermediate: "Spread", word: "Proliferation", category: "gp", sentence: "The proliferation of food trucks in the neighborhood gave everyone dozens of lunch choices." },
  { id: "w300", basic: "Shrinkage", intermediate: "Decline", word: "Diminution", category: "gp", sentence: "Turning down the bright lights caused a gentle diminution of the room\'s harsh glare." },
  { id: "w301", basic: "Advance", intermediate: "Progress", word: "Progression", category: "gp", sentence: "Learning guitar chords shows a steady progression from basic finger placements to fast solos." },
  { id: "w302", basic: "Decay", intermediate: "Decline", word: "Decadence", category: "gp", sentence: "Eating chocolate cake for breakfast felt like a moment of pure, silly decadence." },
  { id: "w303", basic: "Blend", intermediate: "Mix", word: "Fusion", category: "gp", sentence: "The restaurant serves an amazing fusion of Italian pasta and traditional Japanese flavors." },
  { id: "w304", basic: "Division", intermediate: "Separation", word: "Disjunction", category: "gp", sentence: "There was a clear disjunction between how clean he claimed his room was and the pile of clothes on the floor." },
  { id: "w305", basic: "Modernity", intermediate: "Currency", word: "Novelty", category: "gp", sentence: "Trying out a new board game brings a sense of novelty to regular family game nights." },
  { id: "w306", basic: "Antiquity", intermediate: "Oldness", word: "Venerability", category: "gp", sentence: "The ancient oak tree in the town park had a quiet venerability that made everyone stop and admire it." },
  { id: "w307", basic: "Outcast", intermediate: "Rejected person", word: "Exile", category: "gp", sentence: "Being forced to sit on the bench after a penalty felt like a temporary exile for the hockey player." },
  { id: "w308", basic: "Hero", intermediate: "Model", word: "Luminard", category: "gp", sentence: "The veteran chef was treated as a luminard of home cooking, known for making complex dishes simple." },
  { id: "w309", basic: "Rival", intermediate: "Opponent", word: "Antagonist", category: "gp", sentence: "In the video game, the main antagonist keeps placing obstacles to stop you from reaching the tower." },
  { id: "w310", basic: "Partner", intermediate: "Ally", word: "Confederate", category: "gp", sentence: "He found an enthusiastic confederate in his brother when planning a surprise party for their parents." },
  { id: "w311", basic: "Neglect", intermediate: "Disregard", word: "Inattention", category: "gp", sentence: "A brief moment of inattention while chopping vegetables resulted in a small cut on his thumb." },
  { id: "w312", basic: "Attention", intermediate: "Care", word: "Assiduity", category: "gp", sentence: "She studied the map with absolute assiduity so they wouldn\'t get lost on the hiking trail." },
  { id: "w313", basic: "Loyalty", intermediate: "Devotion", word: "Fidelity", category: "gp", sentence: "The movie adapted the original book with impressive fidelity, keeping every major detail intact." },
  { id: "w314", basic: "Betrayal", intermediate: "Treason", word: "Disloyalty", category: "gp", sentence: "Rooting for the opposing team was seen as a hilarious act of disloyalty by his friends." },
  { id: "w315", basic: "Extravagance", intermediate: "Wastefulness", word: "Squandering", category: "gp", sentence: "Spending your entire monthly allowance on day one is a quick way of squandering your money." },
  { id: "w316", basic: "Frugality", intermediate: "Saving", word: "Thrift", category: "gp", sentence: "Shopping at second-hand stores is a great example of smart financial thrift." },
  { id: "w317", basic: "Urgency", intermediate: "Criticality", word: "Exigency", category: "gp", sentence: "The unexpected leak under the sink created an immediate exigency to find a bucket and towels." },
  { id: "w318", basic: "Delay", intermediate: "Postponement", word: "Procrastination", category: "gp", sentence: "Waiting until midnight to start a major assignment is the classic trap of procrastination." },
  { id: "w319", basic: "Ease", intermediate: "Smoothness", word: "Fluency", category: "gp", sentence: "Playing a video game daily builds impressive fluency with the complex controller buttons." },
  { id: "w320", basic: "Difficulty", intermediate: "Hardship", word: "Tribulation", category: "gp", sentence: "Dealing with two flat tires on the same road trip was an unexpected tribulation." },
  { id: "w321", basic: "Evidence", intermediate: "Proof", word: "Substantiation", category: "gp", sentence: "You need to show your receipt as substantiation if you want to return that jacket to the store." },
  { id: "w322", basic: "Disproof", intermediate: "Denial", word: "Refutation", category: "gp", sentence: "Showing the video recording provided a clear refutation of who actually dropped the vase." },
  { id: "w323", basic: "Directness", intermediate: "Clarity", word: "Explicit Statement", category: "gp", sentence: "The recipe included an explicit statement reminding cooks to remove the pan from the heat." },
  { id: "w324", basic: "Evasiveness", intermediate: "Ambiguity", word: "Tergiversation", category: "gp", sentence: "Her constant tergiversation when asked where she wanted to eat dinner drove her friends crazy." },
  { id: "w325", basic: "Certainty", intermediate: "Confidence", word: "Certitude", category: "gp", sentence: "He spoke with absolute certitude when stating that his favorite team would win the match." },
  { id: "w326", basic: "Doubt", intermediate: "Uncertainty", word: "Skepticism", category: "gp", sentence: "She greeted the advertisement\'s claim of \"instant strength gains\" with heavy skepticism." },
  { id: "w327", basic: "Essential", intermediate: "Vital", word: "Imperative", category: "gp", sentence: "It is an absolute imperative to hydrate continuously while running under the hot sun." },
  { id: "w328", basic: "Unnecessary", intermediate: "Extra", word: "Supererogatory", category: "gp", sentence: "Bringing homemade cookies for the whole office was completely supererogatory, but everyone loved it." },
  { id: "w329", basic: "Uniform", intermediate: "Identical", word: "Undifferentiated", category: "gp", sentence: "To an untrained ear, different subgenres of electronic music might sound like an undifferentiated noise." },
  { id: "w330", basic: "Diverse", intermediate: "Mixed", word: "Multifarious", category: "gp", sentence: "The flea market offered multifarious items, from vintage watches to handmade pottery." },
  { id: "w331", basic: "Core", intermediate: "Central point", word: "Crux", category: "gp", sentence: "Finding a reliable babysitter was the crux of their plans for a night out." },
  { id: "w332", basic: "Secondary", intermediate: "Minor", word: "Ancillary", category: "gp", sentence: "Packing extra batteries is an ancillary detail that saves you trouble during a camping trip." },
  { id: "w333", basic: "Broad", intermediate: "Wide", word: "Extensive", category: "gp", sentence: "He did extensive research on different laptop models before deciding which one to buy." },
  { id: "w334", basic: "Narrow", intermediate: "Limited", word: "Circumscribed", category: "gp", sentence: "His physical activity was strictly circumscribed to gentle walking while his ankle healed." },
  { id: "w335", basic: "Show", intermediate: "Present", word: "Expose", category: "gp", sentence: "Cleaning out the garage will expose how many old boxes have been piling up over the years." },
  { id: "w336", basic: "Hide", intermediate: "Cover", word: "Shroud", category: "gp", sentence: "Dense morning fog began to shroud the highway, forcing drivers to slow down." },
  { id: "w337", basic: "Help", intermediate: "Aid", word: "Succor", category: "gp", sentence: "Bringing a thermos of warm soup provided great succor to the cold outdoor workers." },
  { id: "w338", basic: "Stop", intermediate: "Halt", word: "Arrest", category: "gp", sentence: "Taking a quick nap helped arrest the growing headache before it ruined her afternoon." },
  { id: "w339", basic: "Start", intermediate: "Commence", word: "Inaugurate", category: "gp", sentence: "The family decided to inaugurate their new backyard patio by hosting a summer barbecue." },
  { id: "w340", basic: "Cause", intermediate: "Bring about", word: "Precipitate", category: "gp", sentence: "Dropping a heavy weight on the weak floorboards could precipitate a dangerous collapse." },
  { id: "w341", basic: "Spread", intermediate: "Propagate", word: "Promulgate", category: "gp", sentence: "The gym owner posted signs to promulgate the new rules about wiping down equipment." },
  { id: "w342", basic: "Gather", intermediate: "Assemble", word: "Muster", category: "gp", sentence: "He had to muster up all his courage before getting on stage for the karaoke performance." },
  { id: "w343", basic: "Build", intermediate: "Erect", word: "Establish", category: "gp", sentence: "It takes time to establish a healthy sleep routine after working late shifts." },
  { id: "w344", basic: "Destroy", intermediate: "Ruin", word: "Dismantle", category: "gp", sentence: "It took two hours to dismantle the tent and pack it back into the tiny carrying bag." },
  { id: "w345", basic: "Weaken", intermediate: "Sap", word: "Enervate", category: "gp", sentence: "Spending all afternoon pulling weeds in the hot sun will quickly enervate even strong gardeners." },
  { id: "w346", basic: "Strengthen", intermediate: "Reinforce", word: "Fortify", category: "gp", sentence: "Adding an extra layer of insulation helps fortify the house against cold winter drafts." },
  { id: "w347", basic: "Enrich", intermediate: "Improve", word: "Aggrandize", category: "gp", sentence: "Bragging about minor achievements is just a cheap way to try and aggrandize yourself." },
  { id: "w348", basic: "Impoverish", intermediate: "Deprive", word: "Denude", category: "gp", sentence: "A severe caterpillar infestation can denude an entire garden bush of its leaves in days." },
  { id: "w349", basic: "Expand", intermediate: "Enlarge", word: "Dilate", category: "gp", sentence: "Your eyes will naturally dilate when you walk into a dark room to let in more light." },
  { id: "w350", basic: "Reduce", intermediate: "Lessen", word: "Truncate", category: "gp", sentence: "Rain forced us to truncate our picnic and head back inside the house." },
  { id: "w351", basic: "Praise", intermediate: "Commend", word: "Eulogize", category: "gp", sentence: "Family members gathered to eulogize their grandfather, sharing happy stories from his long life." },
  { id: "w352", basic: "Blame", intermediate: "Reproach", word: "Castigate", category: "gp", sentence: "The coach didn\'t hesitate to castigate the team for lack of effort during defensive drills." },
  { id: "w353", basic: "Forgive", intermediate: "Pardon", word: "Absolve", category: "gp", sentence: "Showing proof that you were elsewhere will absolve you from blame for the broken window." },
  { id: "w354", basic: "Accuse", intermediate: "Indict", word: "Arraign", category: "gp", sentence: "In mock trial class, the students learned how the court system works to arraign a suspect." },
  { id: "w355", basic: "Disregard", intermediate: "Ignore", word: "Slight", category: "gp", sentence: "Forgetting to invite her to the casual group lunch felt like an accidental slight." },
  { id: "w356", basic: "Obey", intermediate: "Follow", word: "Adhere to", category: "gp", sentence: "Make sure you strictly adhere to the baking times given in the pastry recipe." },
  { id: "w357", basic: "Reject", intermediate: "Dismiss", word: "Jettison", category: "gp", sentence: "They decided to jettison heavy items from their backpacks to lighten the load for the steep hike." },
  { id: "w358", basic: "Accept", intermediate: "Endorse", word: "Ratify", category: "gp", sentence: "Both roommates must ratify the new cleaning schedule before it becomes an official house rule." },
  { id: "w359", basic: "Demand", intermediate: "Exact", word: "Enjoin", category: "gp", sentence: "The apartment manager had to enjoin tenants from playing loud music past midnight." },
  { id: "w360", basic: "Suggest", intermediate: "Intimate", word: "Insinuate", category: "gp", sentence: "It isn\'t fair to insinuate that he lost the game on purpose just because he made one mistake." },
  { id: "w361", basic: "Claim", intermediate: "Maintain", word: "Aver", category: "gp", sentence: "I can aver that her homemade pizza is the best you will ever taste." },
  { id: "w362", basic: "Prove", intermediate: "Demonstrate", word: "Vindicate", category: "gp", sentence: "Finding the missing receipt served to vindicate his claim that he had already paid his share." },
  { id: "w363", basic: "Disprove", intermediate: "Rebut", word: "Gainsay", category: "gp", sentence: "The evidence of the scoreboard was something no fan of the losing team could gainsay." },
  { id: "w364", basic: "Question", intermediate: "Dispute", word: "Impugn", category: "gp", sentence: "It was rude of him to impugn her honesty just because she misplaced her wallet." },
  { id: "w365", basic: "Think", intermediate: "Deliberate", word: "Ruminate", category: "gp", sentence: "He likes to go for long solo walks to ruminate on life decisions and career goals." },
  { id: "w366", basic: "Understand", intermediate: "Grasp", word: "Apprehend", category: "gp", sentence: "Beginners sometimes struggle to apprehend the full rules of chess on their first try." },
  { id: "w367", basic: "Remember", intermediate: "Retain", word: "Recall", category: "gp", sentence: "Try to recall where you last placed your car keys before searching the whole house." },
  { id: "w368", basic: "Notice", intermediate: "Observe", word: "Perceive", category: "gp", sentence: "Dogs can perceive subtle sounds that human ears miss entirely." },
  { id: "w369", basic: "Deceive", intermediate: "Dupe", word: "Subterfuge", category: "gp", sentence: "Using a fake box to hide the real birthday gift was a fun little bit of subterfuge." },
  { id: "w370", basic: "Encourage", intermediate: "Stimulate", word: "Galvanize", category: "gp", sentence: "Seeing their team fall behind by ten points served to galvanize the players into action." },
  { id: "w371", basic: "Discourage", intermediate: "Deter", word: "Stifle", category: "gp", sentence: "Trying to stifle a loud yawn during a quiet movie is always a difficult challenge." },
  { id: "w372", basic: "Exaggerate", intermediate: "Overstate", word: "Embellish", category: "gp", sentence: "Storytellers often embellish their personal anecdotes to make their friends laugh louder." },
  { id: "w373", basic: "Minimize", intermediate: "Belittle", word: "Depreciate", category: "gp", sentence: "Leaving a high-end bicycle out in the rain will quickly depreciate its resale value." },
  { id: "w374", basic: "Simplify", intermediate: "Clarify", word: "Elucidate", category: "gp", sentence: "The graphic diagram helped elucidate how the complex plumbing system worked." },
  { id: "w375", basic: "Complicate", intermediate: "Obscure", word: "Entangle", category: "gp", sentence: "Leaving loose cords behind the TV desk will quickly entangle them into a messy knot." },
  { id: "w376", basic: "Connect", intermediate: "Join", word: "Concatenate", category: "gp", sentence: "The software app allows you to concatenate multiple short video clips into one continuous reel." },
  { id: "w377", basic: "Separate", intermediate: "Detach", word: "Disarticulate", category: "gp", sentence: "The mechanic had to disarticulate the front bumper to reach the damaged headlight cable." },
  { id: "w378", basic: "Replace", intermediate: "Displace", word: "Supplant", category: "gp", sentence: "Digital streaming services have managed to supplant physical DVDs for most movie viewers." },
  { id: "w379", basic: "Restore", intermediate: "Rebuild", word: "Rehabilitate", category: "gp", sentence: "The trainer worked for months to rehabilitate the athlete\'s injured shoulder." },
  { id: "w380", basic: "Create", intermediate: "Produce", word: "Engender", category: "gp", sentence: "Keeping clear communication with your teammates will engender a strong sense of trust." },
  { id: "w381", basic: "Transform", intermediate: "Alter", word: "Metamorphose", category: "gp", sentence: "Watching a caterpillar metamorphose into a butterfly is one of nature\'s best sights." },
  { id: "w382", basic: "Grow", intermediate: "Expand", word: "Procreate", category: "gp", sentence: "Gardeners cultivate healthy soil so that helpful earthworm populations can procreate naturally." },
  { id: "w383", basic: "Shrink", intermediate: "Contract", word: "Wither", category: "gp", sentence: "Without regular watering, houseplants will start to droop and wither in the sun." },
  { id: "w384", basic: "Rise", intermediate: "Soar", word: "Surge", category: "gp", sentence: "Electricity usage will surge on hot summer afternoons as everyone turns on their air conditioning." },
  { id: "w385", basic: "Fall", intermediate: "Drop", word: "Nosedive", category: "gp", sentence: "Battery life can nosedive rapidly if you stream high-definition video with full screen brightness." },
  { id: "w386", basic: "Pass", intermediate: "Exceed", word: "Outstrip", category: "gp", sentence: "Demand for the new running shoe model began to outstrip the store\'s limited stock." },
  { id: "w387", basic: "Stay", intermediate: "Remain", word: "Abide", category: "gp", sentence: "If you want to play board games here, you have to abide by the official rulebook." },
  { id: "w388", basic: "Waste", intermediate: "Misspend", word: "Fritter away", category: "gp", sentence: "Do not fritter away your study time by checking social media every two minutes." },
  { id: "w389", basic: "Save", intermediate: "Hoard", word: "Husband", category: "gp", sentence: "During long wilderness hikes, you must husband your fresh water supply carefully." },
  { id: "w390", basic: "Avoid", intermediate: "Bypass", word: "Circumvent", category: "gp", sentence: "We took a scenic side road to circumvent the heavy traffic delay on the main highway." },
  { id: "w391", basic: "Limit", intermediate: "Restrain", word: "Trammel", category: "gp", sentence: "High shoes and tight jeans can trammel your freedom of movement while dancing." },
  { id: "w392", basic: "Combine", intermediate: "Fuse", word: "Synthesize", category: "gp", sentence: "A good review will synthesize different opinions into a helpful buying guide." },
  { id: "w393", basic: "Improve", intermediate: "Better", word: "Ameliorate", category: "gp", sentence: "Taking a warm shower can help ameliorate tight muscle soreness after a heavy workout." },
  { id: "w394", basic: "Change", intermediate: "Alter", word: "Transmute", category: "gp", sentence: "A great chef can transmute basic, cheap ingredients into a high-end gourmet meal." },
  { id: "w395", basic: "Deepen", intermediate: "Intensify", word: "Heighten", category: "gp", sentence: "Dimming the living room lights helps heighten the scary atmosphere of a horror movie." },
  { id: "w396", basic: "Broaden", intermediate: "Extend", word: "Widen", category: "gp", sentence: "Opening the windows will help widen the air circulation throughout the house." },
  { id: "w397", basic: "Narrow", intermediate: "Restrict", word: "Constrain", category: "gp", sentence: "Tight shoes will constrain your toes and cause discomfort on long walks." },
  { id: "w398", basic: "Sharpen", intermediate: "Hone", word: "Refine", category: "gp", sentence: "Practice every day to refine your drawing skills and improve your line work." },
  { id: "w399", basic: "Dull", intermediate: "Deactivate", word: "Blunt", category: "gp", sentence: "Cutting thick cardboard with kitchen scissors will blunt the sharp blades over time." },
  { id: "w400", basic: "Active", intermediate: "Dynamic", word: "Vibrant", category: "gp", sentence: "The morning market was filled with vibrant colors from fresh fruit and blooming flowers." },
];
