// MaxWord vocabulary bank — sourced from the A-Level GP Vocabulary Masterlist (200 words).
// This file is pure data — no app logic. Safe to hand-edit or extend without touching index.html.
//
// Data shape: each entry has a 3-tier progression (basic -> intermediate -> advanced).
// The QUESTION shown to the player is always the ADVANCED word.
// The 3 answer choices are drawn from BASIC/INTERMEDIATE words only, with exactly
// one of the three being the correct basic/intermediate match for that advanced word.
// `sentence` is a contextual example sentence demonstrating the advanced word in use.

export const CATEGORIES = [
  { key: "gp", label: "GP Vocabulary" },
];

export const WORDS = [
  { id: "w001", basic: "Show", intermediate: "Demonstrate", word: "Evince", category: "gp", sentence: "The policy proposals evince a clear intent to prioritize sustainability over short-term profits." },
  { id: "w002", basic: "Hide", intermediate: "Conceal", word: "Obfuscate", category: "gp", sentence: "State media often attempts to obfuscate the reality of financial crises through selective data reporting." },
  { id: "w003", basic: "Help", intermediate: "Assist", word: "Facilitate", category: "gp", sentence: "Digital infrastructure projects can facilitate cross-border trade in developing regions." },
  { id: "w004", basic: "Stop", intermediate: "Prevent", word: "Thwart", category: "gp", sentence: "Robust security regulations managed to thwart cyber threats targeted at national infrastructure." },
  { id: "w005", basic: "Start", intermediate: "Initiate", word: "Instigate", category: "gp", sentence: "Unfair labor conditions helped to instigate widespread union strikes across the manufacturing sector." },
  { id: "w006", basic: "Cause", intermediate: "Produce", word: "Engender", category: "gp", sentence: "Unregulated social media platforms can engender deep political polarization within democratic societies." },
  { id: "w007", basic: "Spread", intermediate: "Scatter", word: "Disseminate", category: "gp", sentence: "Independent news outlets work to disseminate accurate information during public emergencies." },
  { id: "w008", basic: "Gather", intermediate: "Accumulate", word: "Aggregate", category: "gp", sentence: "Data analytics tools aggregate consumer metrics to predict global market movements." },
  { id: "w009", basic: "Build", intermediate: "Construct", word: "Fabricate", category: "gp", sentence: "Bad actors can easily fabricate convincing deepfake videos using open-source tools." },
  { id: "w010", basic: "Destroy", intermediate: "Devastate", word: "Annihilate", category: "gp", sentence: "Nuclear proliferation risks weapons systems that could annihilate major population centers." },
  { id: "w011", basic: "Weak", intermediate: "Fragile", word: "Precarious", category: "gp", sentence: "Laborers in gig economy positions remain in precarious financial situations without traditional safety nets." },
  { id: "w012", basic: "Strong", intermediate: "Robust", word: "Resilient", category: "gp", sentence: "A diversified economy makes a country far more resilient against external supply chain shocks." },
  { id: "w013", basic: "Rich", intermediate: "Wealthy", word: "Affluent", category: "gp", sentence: "Consumers in affluent nations account for a disproportionate share of international resource consumption." },
  { id: "w014", basic: "Poor", intermediate: "Needy", word: "Destitute", category: "gp", sentence: "Natural disasters can instantly leave entire rural communities completely destitute." },
  { id: "w015", basic: "Large", intermediate: "Substantial", word: "Prodigious", category: "gp", sentence: "The tech sector requires prodigious amounts of electricity to sustain growing data centers." },
  { id: "w016", basic: "Small", intermediate: "Minor", word: "Negligible", category: "gp", sentence: "Statistical models show that the environmental impact of the new policy will be negligible." },
  { id: "w017", basic: "Shortage", intermediate: "Scarcity", word: "Paucity", category: "gp", sentence: "A persistent paucity of skilled healthcare staff hinders rural clinic operations worldwide." },
  { id: "w018", basic: "Plenty", intermediate: "Abundance", word: "Profusion", category: "gp", sentence: "The profusion of online streaming options has fragmented traditional media audiences." },
  { id: "w019", basic: "Old", intermediate: "Outdated", word: "Anachronistic", category: "gp", sentence: "Relying solely on coal power generation is increasingly viewed as anachronistic in the modern energy landscape." },
  { id: "w020", basic: "New", intermediate: "Novel", word: "Unprecedented", category: "gp", sentence: "The rapid adoption of generative AI represents an unprecedented shift in information management." },
  { id: "w021", basic: "Quick", intermediate: "Rapid", word: "Expeditious", category: "gp", sentence: "International relief efforts require expeditious administrative procedures to save lives." },
  { id: "w022", basic: "Slow", intermediate: "Sluggish", word: "Lethargic", category: "gp", sentence: "Bureaucratic friction can cause a lethargic official response to sudden economic crises." },
  { id: "w023", basic: "Clear", intermediate: "Apparent", word: "Manifest", category: "gp", sentence: "The consequences of climate change have become manifest through frequent extreme weather events." },
  { id: "w024", basic: "Secret", intermediate: "Hidden", word: "Clandestine", category: "gp", sentence: "Intelligence agencies often conduct clandestine operations to safeguard national security interests." },
  { id: "w025", basic: "False", intermediate: "Fraudulent", word: "Spurious", category: "gp", sentence: "Academic journals rigorously peer-review submissions to eliminate spurious research claims." },
  { id: "w026", basic: "True", intermediate: "Genuine", word: "Authentic", category: "gp", sentence: "Archival documents provide authentic historical insights into early diplomatic treaties." },
  { id: "w027", basic: "Simple", intermediate: "Basic", word: "Rudimentary", category: "gp", sentence: "Early space initiatives operated with rudimentary computer systems compared to modern standards." },
  { id: "w028", basic: "Complex", intermediate: "Intricate", word: "Labyrinthine", category: "gp", sentence: "Navigating the labyrinthine legal systems of international trade requires specialized legal counsel." },
  { id: "w029", basic: "Dangerous", intermediate: "Perilous", word: "Hazardous", category: "gp", sentence: "Transporting industrial waste through urban zones remains an inherently hazardous operation." },
  { id: "w030", basic: "Safe", intermediate: "Secure", word: "Invulnerable", category: "gp", sentence: "No financial institution can consider itself completely invulnerable to global economic recessions." },
  { id: "w031", basic: "Harmful", intermediate: "Injurious", word: "Inimical", category: "gp", sentence: "High import tariffs can prove inimical to long-term international economic cooperation." },
  { id: "w032", basic: "Useful", intermediate: "Beneficial", word: "Advantageous", category: "gp", sentence: "Tax incentives for clean energy startups make investment far more advantageous." },
  { id: "w033", basic: "Equal", intermediate: "Equivalent", word: "Tantamount", category: "gp", sentence: "Failing to act against corporate corruption is tantamount to endorsing unlawful behavior." },
  { id: "w034", basic: "Different", intermediate: "Distinct", word: "Disparate", category: "gp", sentence: "A successful coalition must harmonize the disparate political agendas of its member groups." },
  { id: "w035", basic: "Continuous", intermediate: "Unceasing", word: "Incessant", category: "gp", sentence: "The incessant news cycle often prioritizes sensational breaking stories over deep analysis." },
  { id: "w036", basic: "Temporary", intermediate: "Transient", word: "Ephemeral", category: "gp", sentence: "Modern viral trends typically enjoy ephemeral success before fading from public interest." },
  { id: "w037", basic: "Eternal", intermediate: "Perpetual", word: "Immutable", category: "gp", sentence: "Basic human ethical principles ought to be viewed as immutable rights across cultures." },
  { id: "w038", basic: "Predictable", intermediate: "Foreseeable", word: "Inevitable", category: "gp", sentence: "Structural automation makes the transformation of traditional manufacturing jobs inevitable." },
  { id: "w039", basic: "Random", intermediate: "Arbitrary", word: "Capricious", category: "gp", sentence: "Regulatory policies that are too capricious discourage stable long-term foreign investment." },
  { id: "w040", basic: "Important", intermediate: "Crucial", word: "Paramount", category: "gp", sentence: "Public health safety must remain the paramount concern when approving new pharmaceutical products." },
  { id: "w041", basic: "Useless", intermediate: "Futile", word: "Ineffectual", category: "gp", sentence: "Symbolic policy statements prove ineffectual without concrete legislative funding." },
  { id: "w042", basic: "Bias", intermediate: "Partiality", word: "Partisanship", category: "gp", sentence: "Deepening political partisanship frequently stalls legislative progress in congress." },
  { id: "w043", basic: "Fairness", intermediate: "Equity", word: "Impartiality", category: "gp", sentence: "International judicial bodies rely on absolute impartiality to maintain global credibility." },
  { id: "w044", basic: "Freedom", intermediate: "Liberty", word: "Autonomy", category: "gp", sentence: "Higher education institutions demand institutional autonomy to pursue uninhibited scientific research." },
  { id: "w045", basic: "Control", intermediate: "Domination", word: "Hegemony", category: "gp", sentence: "Global tech platforms exert digital hegemony over international information flows." },
  { id: "w046", basic: "Rebellion", intermediate: "Defiance", word: "Insubordination", category: "gp", sentence: "Military hierarchy strictly disciplines any act of direct insubordination." },
  { id: "w047", basic: "Agreement", intermediate: "Consensus", word: "Unanimity", category: "gp", sentence: "Achieving complete unanimity among international partners on climate goals remains difficult." },
  { id: "w048", basic: "Argument", intermediate: "Dispute", word: "Polemic", category: "gp", sentence: "The author's latest book serves as a sharp polemic against modern corporate capitalism." },
  { id: "w049", basic: "Division", intermediate: "Separation", word: "Schism", category: "gp", sentence: "Divergent economic priorities caused a political schism among allied trade nations." },
  { id: "w050", basic: "Peak", intermediate: "Climax", word: "Zenith", category: "gp", sentence: "Historical records show the empire reached its cultural zenith during the golden century." },
  { id: "w051", basic: "Bottom", intermediate: "Low", word: "Nadir", category: "gp", sentence: "The country's diplomatic relations hit their nadir following the breach of international treaties." },
  { id: "w052", basic: "Support", intermediate: "Endorse", word: "Champion", category: "gp", sentence: "Dedicated policy groups champion environmental justice within marginalized communities." },
  { id: "w053", basic: "Attack", intermediate: "Criticize", word: "Denounce", category: "gp", sentence: "World leaders stepped forward to publicly denounce human rights violations." },
  { id: "w054", basic: "Forgive", intermediate: "Absolve", word: "Exonerate", category: "gp", sentence: "DNA testing evidence managed to fully exonerate the falsely accused individual." },
  { id: "w055", basic: "Blame", intermediate: "Implicate", word: "Incriminate", category: "gp", sentence: "Financial audit trails can incriminate corporate executives involved in fraud." },
  { id: "w056", basic: "Praise", intermediate: "Laud", word: "Exalt", category: "gp", sentence: "National propaganda campaigns often exalt historic victories to foster patriotism." },
  { id: "w057", basic: "Hate", intermediate: "Detest", word: "Abhor", category: "gp", sentence: "Civilized legal frameworks abhor the use of forced confessions in criminal proceedings." },
  { id: "w058", basic: "Ignore", intermediate: "Disregard", word: "Flout", category: "gp", sentence: "Corporations that flout safety laws must face significant structural penalties." },
  { id: "w059", basic: "Obey", intermediate: "Comply", word: "Acquiesce", category: "gp", sentence: "Citizens rarely acquiesce to authoritarian policies without domestic resistance over time." },
  { id: "w060", basic: "Refuse", intermediate: "Reject", word: "Repudiate", category: "gp", sentence: "Modern governments must formally repudiate historic colonial agreements." },
  { id: "w061", basic: "Accept", intermediate: "Embrace", word: "Sanction", category: "gp", sentence: "International bodies may sanction trade restrictions against law-breaking states." },
  { id: "w062", basic: "Demand", intermediate: "Require", word: "Mandate", category: "gp", sentence: "Constitutional law should mandate transparent elections across democratic states." },
  { id: "w063", basic: "Suggest", intermediate: "Propose", word: "Posit", category: "gp", sentence: "Economists posit that technological innovation drives long-term productivity gains." },
  { id: "w064", basic: "Claim", intermediate: "Assert", word: "Contend", category: "gp", sentence: "Legal analysts contend that existing copyright frameworks fail to address AI-generated content." },
  { id: "w065", basic: "Prove", intermediate: "Verify", word: "Corroborate", category: "gp", sentence: "Satellite imaging data helps corroborate news reports of environmental damage." },
  { id: "w066", basic: "Disprove", intermediate: "Refute", word: "Rebut", category: "gp", sentence: "Defense attorneys prepared extensive counter-evidence to rebut prosecution claims." },
  { id: "w067", basic: "Doubt", intermediate: "Question", word: "Query", category: "gp", sentence: "Independent auditors raised questions to query missing corporate financial records." },
  { id: "w068", basic: "Think", intermediate: "Ponder", word: "Cogitate", category: "gp", sentence: "Legal scholars must cogitate on the ethical boundaries of gene-editing technologies." },
  { id: "w069", basic: "Understand", intermediate: "Comprehend", word: "Fathom", category: "gp", sentence: "Researchers struggle to fathom the full scale of deep-sea ecological biodiversity." },
  { id: "w070", basic: "Remember", intermediate: "Recall", word: "Recollect", category: "gp", sentence: "Witnesses were asked to recollect specific details surrounding the emergency event." },
  { id: "w071", basic: "Notice", intermediate: "Perceive", word: "Discern", category: "gp", sentence: "Analytical models help data scientists discern underlying demographic shifts." },
  { id: "w072", basic: "Mislead", intermediate: "Deceive", word: "Beguile", category: "gp", sentence: "Marketing campaigns can beguile consumers into purchasing unnecessary products." },
  { id: "w073", basic: "Encourage", intermediate: "Foster", word: "Nurture", category: "gp", sentence: "Government grants help nurture promising green technology research projects." },
  { id: "w074", basic: "Discourage", intermediate: "Deter", word: "Inhibit", category: "gp", sentence: "Excessive taxation can inhibit technological research and market expansion." },
  { id: "w075", basic: "Exaggerate", intermediate: "Overstate", word: "Hyperbolize", category: "gp", sentence: "Media headlines tend to hyperbolize temporary economic downturns." },
  { id: "w076", basic: "Minimize", intermediate: "Downplay", word: "Trivialise", category: "gp", sentence: "Public discussions should not trivialise mental health issues among young demographics." },
  { id: "w077", basic: "Simplify", intermediate: "Streamline", word: "Distil", category: "gp", sentence: "Researchers must distil vast datasets into clear recommendations for policymakers." },
  { id: "w078", basic: "Complicate", intermediate: "Confuse", word: "Confound", category: "gp", sentence: "Unexpected economic variables can confound financial growth projections." },
  { id: "w079", basic: "Connect", intermediate: "Link", word: "Correlate", category: "gp", sentence: "Epidemiological studies correlate high urban pollution levels with respiratory illness." },
  { id: "w080", basic: "Separate", intermediate: "Isolate", word: "Segregate", category: "gp", sentence: "Historic city planning worked to segregate residential sectors by social class." },
  { id: "w081", basic: "Replace", intermediate: "Substitute", word: "Supersede", category: "gp", sentence: "Advanced satellite links will soon supersede traditional copper communications infrastructure." },
  { id: "w082", basic: "Restore", intermediate: "Renew", word: "Rejuvenate", category: "gp", sentence: "Urban investment plans aim to rejuvenate declining industrial zones." },
  { id: "w083", basic: "Create", intermediate: "Generate", word: "Instantiate", category: "gp", sentence: "Emerging smart cities instantiate modern sustainable architectural theory." },
  { id: "w084", basic: "Transform", intermediate: "Convert", word: "Transmute", category: "gp", sentence: "Efficient recycling facilities can transmute industrial waste into usable manufacturing fuel." },
  { id: "w085", basic: "Grow", intermediate: "Expand", word: "Proliferate", category: "gp", sentence: "Digital financial tools continue to proliferate across emerging global markets." },
  { id: "w086", basic: "Shrink", intermediate: "Diminish", word: "Dwindle", category: "gp", sentence: "Natural gas reserves continue to dwindle under intense global industrial demand." },
  { id: "w087", basic: "Rise", intermediate: "Ascend", word: "Surge", category: "gp", sentence: "International travel demand experiences a surge following peak holiday periods." },
  { id: "w088", basic: "Fall", intermediate: "Decline", word: "Plummet", category: "gp", sentence: "Stock valuations can plummet rapidly after unexpected regulatory announcements." },
  { id: "w089", basic: "Pass", intermediate: "Surpass", word: "Transcend", category: "gp", sentence: "Art and literature possess an inherent ability to transcend linguistic barriers." },
  { id: "w090", basic: "Stay", intermediate: "Remain", word: "Persist", category: "gp", sentence: "Systemic economic inequality can persist across generations without active social intervention." },
  { id: "w091", basic: "Waste", intermediate: "Squander", word: "Dissipate", category: "gp", sentence: "Misinformation scares tend to dissipate once official facts are confirmed." },
  { id: "w092", basic: "Save", intermediate: "Preserve", word: "Conserve", category: "gp", sentence: "Developing economies must conserve finite freshwater supplies to safeguard agriculture." },
  { id: "w093", basic: "Strict", intermediate: "Rigorous", word: "Draconian", category: "gp", sentence: "Civil liberties groups criticize draconian public surveillance legislation." },
  { id: "w094", basic: "Gentle", intermediate: "Mild", word: "Benign", category: "gp", sentence: "Certain automated algorithms play a benign role in organizing digital archives." },
  { id: "w095", basic: "Loud", intermediate: "Vocal", word: "Vociferous", category: "gp", sentence: "Consumer advocacy organizations have been vociferous in demanding product safety data." },
  { id: "w096", basic: "Quiet", intermediate: "Subdued", word: "Reticent", category: "gp", sentence: "Officials remained reticent regarding pending trade negotiation details." },
  { id: "w097", basic: "Avoid", intermediate: "Evade", word: "Eschew", category: "gp", sentence: "Ethical consumers increasingly eschew products linked to worker exploitation." },
  { id: "w098", basic: "Limit", intermediate: "Restrict", word: "Circumscribe", category: "gp", sentence: "Constitutional provisions serve to circumscribe state powers over private citizens." },
  { id: "w099", basic: "Combine", intermediate: "Merge", word: "Amalgamate", category: "gp", sentence: "Corporate mergers attempt to amalgamate logistics networks to reduce total costs." },
  { id: "w100", basic: "Improve", intermediate: "Enhance", word: "Ameliorate", category: "gp", sentence: "Direct policy aid can ameliorate immediate economic burdens for low-income citizens." },
  { id: "w101", basic: "Change", intermediate: "Modify", word: "Mutate", category: "gp", sentence: "Infectious viruses can mutate quickly, requiring redesigned medical vaccines." },
  { id: "w102", basic: "Deep", intermediate: "Profound", word: "Fathomless", category: "gp", sentence: "Deep ocean trenches remain vast environments with fathomless scientific mysteries." },
  { id: "w103", basic: "Shallow", intermediate: "Superficial", word: "Cursory", category: "gp", sentence: "A cursory reading of the proposal misses key environmental regulatory details." },
  { id: "w104", basic: "Broad", intermediate: "Comprehensive", word: "All-encompassing", category: "gp", sentence: "The new policy framework presents an all-encompassing strategy for clean energy transition." },
  { id: "w105", basic: "Narrow", intermediate: "Parochial", word: "Provincial", category: "gp", sentence: "Isolating trade policies reflects a provincial view of global economic interconnectedness." },
  { id: "w106", basic: "Sharp", intermediate: "Acute", word: "Incisive", category: "gp", sentence: "The journalist's incisive questioning exposed major policy contradictions during the debate." },
  { id: "w107", basic: "Dull", intermediate: "Monotonous", word: "Pedestrian", category: "gp", sentence: "Analysts dismissed the theoretical paper as a pedestrian retread of existing literature." },
  { id: "w108", basic: "Active", intermediate: "Energetic", word: "Vibrant", category: "gp", sentence: "Urban centers benefit economically from having a vibrant arts and media culture." },
  { id: "w109", basic: "Passive", intermediate: "Inactive", word: "Quiescent", category: "gp", sentence: "Volcanoes can remain quiescent for centuries before experiencing sudden eruptions." },
  { id: "w110", basic: "Stubborn", intermediate: "Obstinate", word: "Intransigent", category: "gp", sentence: "Negotiations stalled because both political parties remained completely intransigent." },
  { id: "w111", basic: "Flexible", intermediate: "Adaptable", word: "Malleable", category: "gp", sentence: "Young minds are exceptionally malleable, making early education quality critical." },
  { id: "w112", basic: "Friendly", intermediate: "Amicable", word: "Convivial", category: "gp", sentence: "International diplomatic summits benefit from a convivial negotiating atmosphere." },
  { id: "w113", basic: "Hostile", intermediate: "Antagonistic", word: "Bellicose", category: "gp", sentence: "The foreign minister's bellicose rhetoric escalated border tensions sharply." },
  { id: "w114", basic: "Honest", intermediate: "Candor", word: "Veracious", category: "gp", sentence: "Investigative reporting must rely exclusively on veracious eyewitness testimonies." },
  { id: "w115", basic: "Sly", intermediate: "Deceitful", word: "Disingenuous", category: "gp", sentence: "It is disingenuous to argue that economic growth proceeds without environmental costs." },
  { id: "w116", basic: "Proud", intermediate: "Arrogant", word: "Supercilious", category: "gp", sentence: "The executive's supercilious attitude toward critics damaged company PR efforts." },
  { id: "w117", basic: "Humble", intermediate: "Modest", word: "Unpretentious", category: "gp", sentence: "The leader's unpretentious communication style resonated deeply with working-class voters." },
  { id: "w118", basic: "Generous", intermediate: "Magnanimous", word: "Altruistic", category: "gp", sentence: "Philanthropic institutions fund global disease eradication through altruistic initiatives." },
  { id: "w119", basic: "Greedy", intermediate: "Avaricious", word: "Acquisitive", category: "gp", sentence: "Unchecked corporate expansion reflects an acquisitive mindset focused on market dominance." },
  { id: "w120", basic: "Brave", intermediate: "Intrepid", word: "Audacious", category: "gp", sentence: "The startup launched an audacious plan to capture space satellite communications market share." },
  { id: "w121", basic: "Timid", intermediate: "Fearful", word: "Pusillanimous", category: "gp", sentence: "Critics condemned the state's pusillanimous failure to confront systemic corporate corruption." },
  { id: "w122", basic: "Wisdom", intermediate: "Sagacity", word: "Erudition", category: "gp", sentence: "The law professor demonstrated profound historical erudition during the constitutional lecture." },
  { id: "w123", basic: "Folly", intermediate: "Foolishness", word: "Fatuity", category: "gp", sentence: "Policy commentators pointed out the absolute fatuity of cutting education funding to save costs." },
  { id: "w124", basic: "Truth", intermediate: "Veracity", word: "Verity", category: "gp", sentence: "Historical research relies on empirical facts to confirm the verity of official state records." },
  { id: "w125", basic: "Lie", intermediate: "Falsehood", word: "Prevarication", category: "gp", sentence: "Spokespersons who resort to prevarication quickly lose public credibility." },
  { id: "w126", basic: "Peace", intermediate: "Tranquility", word: "Serenity", category: "gp", sentence: "Green national parks offer urban populations necessary spaces of natural serenity." },
  { id: "w127", basic: "Chaos", intermediate: "Turmoil", word: "Pandemonium", category: "gp", sentence: "Financial trading floors erupted into complete pandemonium following the bank crash news." },
  { id: "w128", basic: "Wealth", intermediate: "Prosperity", word: "Opulence", category: "gp", sentence: "Excessive architectural opulence often stands in stark contrast to surrounding urban poverty." },
  { id: "w129", basic: "Poverty", intermediate: "Indigence", word: "Penury", category: "gp", sentence: "Developing regions require international aid to lift rural farming families out of severe penury." },
  { id: "w130", basic: "Order", intermediate: "Hierarchy", word: "Systematization", category: "gp", sentence: "Industrial operations depend on the precise systematization of manufacturing steps." },
  { id: "w131", basic: "Disregard", intermediate: "Neglect", word: "Dereliction", category: "gp", sentence: "Failing to maintain critical bridge infrastructure represents a gross dereliction of civic duty." },
  { id: "w132", basic: "Loyalty", intermediate: "Fidelity", word: "Allegiance", category: "gp", sentence: "Citizens hold dual civic allegiance to local regional communities and the national government." },
  { id: "w133", basic: "Betrayal", intermediate: "Treachery", word: "Perfidy", category: "gp", sentence: "Spying scandal revelations exposed internal perfidy within foreign intelligence agencies." },
  { id: "w134", basic: "Skill", intermediate: "Expertise", word: "Adroitness", category: "gp", sentence: "Negotiators handled delicate diplomatic talks with remarkable strategic adroitness." },
  { id: "w135", basic: "Clumsiness", intermediate: "Ineptitude", word: "Maladroitness", category: "gp", sentence: "Strategic maladroitness by trade representatives led to canceled international agreements." },
  { id: "w136", basic: "Beauty", intermediate: "Aesthetics", word: "Resplendence", category: "gp", sentence: "Historical cultural artifacts displayed incredible artistic resplendence in national museums." },
  { id: "w137", basic: "Ugliness", intermediate: "Unattractiveness", word: "Hideousness", category: "gp", sentence: "Industrial pollution runoff highlights the raw ecological hideousness of unchecked production." },
  { id: "w138", basic: "Clean", intermediate: "Pristine", word: "Immaculate", category: "gp", sentence: "Modern chip fabrication cleanrooms require immaculate operating environments to prevent defects." },
  { id: "w139", basic: "Dirty", intermediate: "Sullied", word: "Squalid", category: "gp", sentence: "Rapid urbanization without housing infrastructure creates squalid living conditions in informal settlements." },
  { id: "w140", basic: "Permanent", intermediate: "Indelible", word: "Irrevocable", category: "gp", sentence: "Executive pardon signatures carry irrevocable legal power within the constitutional system." },
  { id: "w141", basic: "Variable", intermediate: "Fluctuating", word: "Protean", category: "gp", sentence: "The protean nature of digital threats requires flexible defensive cyber software frameworks." },
  { id: "w142", basic: "Similar", intermediate: "Analogous", word: "Homogeneous", category: "gp", sentence: "Globalized consumer platforms risk turning distinct local cultures into a homogeneous mass media format." },
  { id: "w143", basic: "Diverse", intermediate: "Eclectic", word: "Heterogeneous", category: "gp", sentence: "Modern metropolis populations comprise highly heterogeneous social and linguistic backgrounds." },
  { id: "w144", basic: "Central", intermediate: "Pivotal", word: "Focal", category: "gp", sentence: "Reducing carbon emissions forms the focal objective of global climate agreements." },
  { id: "w145", basic: "Peripheral", intermediate: "Marginal", word: "Tangential", category: "gp", sentence: "Debate participants should avoid bringing up tangential topics that derail core legislative discussions." },
  { id: "w146", basic: "Essential", intermediate: "Indispensable", word: "Integral", category: "gp", sentence: "Ethical considerations must remain integral to advanced biotechnology research protocols." },
  { id: "w147", basic: "Extra", intermediate: "Superfluous", word: "Redundant", category: "gp", sentence: "Automated administrative processes render manual paperwork data entry completely redundant." },
  { id: "w148", basic: "Direct", intermediate: "Forthright", word: "Unambiguous", category: "gp", sentence: "Statutory regulations must provide unambiguous instructions to avoid legal misinterpretation." },
  { id: "w149", basic: "Indirect", intermediate: "Circuitous", word: "Oblique", category: "gp", sentence: "The report made oblique references to corporate mismanagement without naming specific executives." },
  { id: "w150", basic: "Urgent", intermediate: "Imperative", word: "Exigent", category: "gp", sentence: "Disasters require exigent crisis response measures to maintain essential public utility services." },
  { id: "w151", basic: "Trivial", intermediate: "Insignificant", word: "Trifling", category: "gp", sentence: "Legal systems should not waste public resources settling trifling private disputes." },
  { id: "w152", basic: "Excessive", intermediate: "Extravagant", word: "Immoderate", category: "gp", sentence: "Uncontrolled capital spending leads to immoderate debt burdens for municipal governments." },
  { id: "w153", basic: "Moderate", intermediate: "Temperate", word: "Abstemious", category: "gp", sentence: "Financial institutions recommend abstemious borrowing practices during unpredictable market cycles." },
  { id: "w154", basic: "Exact", intermediate: "Meticulous", word: "Scrupulous", category: "gp", sentence: "Clinical trial teams must maintain scrupulous records to meet health regulation standards." },
  { id: "w155", basic: "Vague", intermediate: "Ambiguous", word: "Equivocal", category: "gp", sentence: "Survey results yielded equivocal conclusions regarding consumer preference changes." },
  { id: "w156", basic: "Certain", intermediate: "Incontrovertible", word: "Indubitable", category: "gp", sentence: "Forensic science evidence provided indubitable proof of the suspect's involvement." },
  { id: "w157", basic: "Questionable", intermediate: "Dubious", word: "Equivocal", category: "gp", sentence: "Political speeches containing equivocal language frustrate voters seeking firm promises." },
  { id: "w158", basic: "Obvious", intermediate: "Self-evident", word: "Axiomatic", category: "gp", sentence: "It is axiomatic that equal access to education drives broader economic mobility." },
  { id: "w159", basic: "Mysterious", intermediate: "Enigmatic", word: "Arcane", category: "gp", sentence: "Understanding legacy code requires navigating arcane technical software documentation." },
  { id: "w160", basic: "Common", intermediate: "Widespread", word: "Ubiquitous", category: "gp", sentence: "Smartphones have transformed from luxury items into ubiquitous daily necessities globally." },
  { id: "w161", basic: "Rare", intermediate: "Infrequent", word: "Sporadic", category: "gp", sentence: "Wireless network access in remote mountainous areas remains sporadic at best." },
  { id: "w162", basic: "Modern", intermediate: "Contemporary", word: "Cutting-edge", category: "gp", sentence: "Medical research centers require cutting-edge equipment to innovate life-saving treatments." },
  { id: "w163", basic: "Ancient", intermediate: "Archaic", word: "Primeval", category: "gp", sentence: "Protected nature reserves shield primeval rainforest environments from commercial logging operations." },
  { id: "w164", basic: "Foreign", intermediate: "Alien", word: "Exogenous", category: "gp", sentence: "Local markets experienced economic volatility caused by exogenous global energy shocks." },
  { id: "w165", basic: "Local", intermediate: "Indigenous", word: "Endemic", category: "gp", sentence: "Dengue fever remains endemic across tropical regions during seasonal rainfall periods." },
  { id: "w166", basic: "Main", intermediate: "Primary", word: "Predominant", category: "gp", sentence: "Agriculture continues to be the predominant industry driving regional rural economies." },
  { id: "w167", basic: "Secondary", intermediate: "Subordinate", word: "Ancillary", category: "gp", sentence: "Logistics services provide ancillary support essential to the primary manufacturing sector." },
  { id: "w168", basic: "Harm", intermediate: "Detriment", word: "Deleteriousness", category: "gp", sentence: "Environmental impact assessments highlight the deleteriousness of chemical ocean dumping." },
  { id: "w169", basic: "Benefit", intermediate: "Advantage", word: "Utility", category: "gp", sentence: "Renewable energy installations demonstrate immense practical utility in reducing national carbon emissions." },
  { id: "w170", basic: "Agreement", intermediate: "Accord", word: "Concordance", category: "gp", sentence: "Successful treaties reflect absolute diplomatic concordance across all negotiating parties." },
  { id: "w171", basic: "Conflict", intermediate: "Friction", word: "Dissonance", category: "gp", sentence: "A stark cognitive dissonance exists between sustainability pledges and corporate spending realities." },
  { id: "w172", basic: "Victory", intermediate: "Triumph", word: "Ascendancy", category: "gp", sentence: "Digital commerce platforms established market ascendancy over traditional brick-and-mortar stores." },
  { id: "w173", basic: "Defeat", intermediate: "Overthrow", word: "Subversion", category: "gp", sentence: "Foreign propaganda campaigns often aim at the political subversion of democratic elections." },
  { id: "w174", basic: "Growth", intermediate: "Expansion", word: "Augmentation", category: "gp", sentence: "Automation aims at human worker capability augmentation, rather than complete job replacement." },
  { id: "w175", basic: "Loss", intermediate: "Deprivation", word: "Attrition", category: "gp", sentence: "Combat zones experience steady resource attrition as long-term conflicts persist over years." },
  { id: "w176", basic: "Origin", intermediate: "Genesis", word: "Provenance", category: "gp", sentence: "Art historians trace the precise provenance of ancient artifacts before museum display." },
  { id: "w177", basic: "End", intermediate: "Termination", word: "Cessation", category: "gp", sentence: "Treaties require an immediate cessation of military hostilities along disputed border lines." },
  { id: "w178", basic: "Danger", intermediate: "Jeopardy", word: "Peril", category: "gp", sentence: "Coastal regions face severe ecological peril as sea levels rise over the coming decades." },
  { id: "w179", basic: "Safety", intermediate: "Protection", word: "Sanctuary", category: "gp", sentence: "Marine protected reserves offer essential sanctuary for endangered coral reef species." },
  { id: "w180", basic: "Force", intermediate: "Coercion", word: "Duress", category: "gp", sentence: "Contracts signed under political duress are legally invalid in international courts." },
  { id: "w181", basic: "Choice", intermediate: "Volition", word: "Discretion", category: "gp", sentence: "Judges hold absolute legal discretion when sentencing offenders within statutory limits." },
  { id: "w182", basic: "Duty", intermediate: "Obligation", word: "Imperative", category: "gp", sentence: "Environmental sustainability has become an economic imperative for forward-thinking corporations." },
  { id: "w183", basic: "Right", intermediate: "Entitlement", word: "Prerogative", category: "gp", sentence: "Executive pardons remain the constitutional prerogative of state heads." },
  { id: "w184", basic: "Policy", intermediate: "Doctrine", word: "Tenet", category: "gp", sentence: "Secular governance maintains the essential tenet of separating religious doctrine from law." },
  { id: "w185", basic: "Rule", intermediate: "Mandate", word: "Precept", category: "gp", sentence: "Rule of law serves as a foundational precept for all democratic legal systems." },
  { id: "w186", basic: "Leader", intermediate: "Figurehead", word: "Lynchpin", category: "gp", sentence: "Semiconductor manufacturing acts as the critical technological lynchpin of the modern global economy." },
  { id: "w187", basic: "Follower", intermediate: "Adherent", word: "Acolyte", category: "gp", sentence: "The political candidate drew dedicated support from every loyal campaign acolyte." },
  { id: "w188", basic: "Crowd", intermediate: "Multitude", word: "Horde", category: "gp", sentence: "Public transit stations must handle a vast horde of commuters during peak urban rush hours." },
  { id: "w189", basic: "Solitude", intermediate: "Isolation", word: "Seclusion", category: "gp", sentence: "Academic retreat centers offer quiet seclusion conducive to intensive literary research." },
  { id: "w190", basic: "Speech", intermediate: "Rhetoric", word: "Discourse", category: "gp", sentence: "Respectful public discourse remains essential for healthy democratic decision-making processes." },
  { id: "w191", basic: "Silence", intermediate: "Taciturnity", word: "Reticence", category: "gp", sentence: "The witness showed extreme reticence when questioned about institutional corruption." },
  { id: "w192", basic: "Vision", intermediate: "Foresight", word: "Prescience", category: "gp", sentence: "The analyst's early writings displayed remarkable prescience regarding the modern digital shift." },
  { id: "w193", basic: "Blindness", intermediate: "Ignorance", word: "Myopia", category: "gp", sentence: "Short-sighted economic myopia leads politicians to neglect long-term infrastructure investment." },
  { id: "w194", basic: "Modernity", intermediate: "Advancement", word: "Contemporary State", category: "gp", sentence: "The contemporary state of automated manufacturing relies heavily on robotics and machine learning." },
  { id: "w195", basic: "Tradition", intermediate: "Heritage", word: "Customary Practice", category: "gp", sentence: "Agricultural communities rely on customary practice passed down across generations." },
  { id: "w196", basic: "Trend", intermediate: "Phenomenon", word: "Zeitgeist", category: "gp", sentence: "Capturing the cultural zeitgeist is essential for successful global advertising campaigns." },
  { id: "w197", basic: "Outcast", intermediate: "Pariah", word: "Ostracized Individual", category: "gp", sentence: "Whistleblowers often face life as an ostracized individual within their former industries." },
  { id: "w198", basic: "Master", intermediate: "Paragon", word: "Exemplar", category: "gp", sentence: "The renewable energy company serves as an operational exemplar for corporate green transition." },
  { id: "w199", basic: "Copy", intermediate: "Replica", word: "Simulacrum", category: "gp", sentence: "Virtual reality software creates a digital simulacrum of real-world training environments." },
  { id: "w200", basic: "Opposite", intermediate: "Inverse", word: "Antithesis", category: "gp", sentence: "Monopolistic market control represents the absolute antithesis of free market competition." },
];
